"""Generates src/LocalizationData.h: the game's OWN wording (from global.yldb in each
language's RPF -- see dump_labels.py) for the 9 category names and the "Dead Eye" term,
in Localization::Language enum order.

Regenerate:  python tools/gen_localization.py   (needs the GXT folder's global_<lang>.yldb,
extracted with RDR2-RPF-Tool from update_3.rpf x64/data/lang/<lang>_rel.rpf).
"""
import struct, sys
import xml.etree.ElementTree as ET
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
import dump_labels as d

# Localization::Language enum order -> (yldb name, code)
ORDER = [('american','en-US'),('french','fr-FR'),('german','de-DE'),('italian','it-IT'),
         ('spanish','es-ES'),('brazilian','pt-BR'),('polish','pl-PL'),('russian','ru-RU'),
         ('korean','ko-KR'),('chinesetrad','zh-TW'),('japanese','ja-JP'),('mexican','es-MX'),
         ('chinesesimp','zh-CN')]
# Category enum order (ChallengeCheat.h) -> challengeNameLabel
CATEGORY_LABELS = ['ACBANDIT','ACEXPLORER','ACGAMBLER','ACHERBALIST','ACHORSEMANSHIP',
                   'ACMASTERHUNTER','ACSHARPSHOOTER','ACSURVIVALIST','ACWEAPONS']
# Label name unknown: found by matching the en-US text "Dead Eye" and confirming the same
# hash yields the game's real Dead Eye term in every language (0x6788AE48).
DEADEYE_HASH = 0x6788AE48

def rank_labels():
    """rankDescLabel per rank (1-10) for each category root, in Category enum order."""
    root = ET.parse(d.META / 'challenges_sp.meta').getroot()
    out = []
    for it in root.find('challenges'):
        if it.find('name').text.endswith('_ROOT'):
            assert it.find('uiInfo/challengeNameLabel').text == CATEGORY_LABELS[len(out)]
            out.append([r.find('uiInfo/rankDescLabel').text for r in it.find('ranks').findall('Item')])
    assert len(out) == 9 and all(len(r) == 10 for r in out)
    return out

def lookup(b, h):
    vals = {v for o in d.find_all(b, struct.pack('<I', h)) if (v := d.resolve(b, o))}
    assert len(vals) == 1, (hex(h), vals)
    v = vals.pop().replace('\u00a0', ' ')  # NBSP renders as tofu in the menu font
    return v

def cstr(s):
    return '"' + s.replace(chr(92), chr(92) * 2).replace('"', chr(92) + '"') + '"'

def main():
    blobs = {n: (d.GXT / f'global_{n}.yldb').read_bytes() for n, _ in ORDER}
    out = ['// GENERATED by tools/gen_localization.py from the game\'s own global.yldb text -- do not edit.',
           '// One row per Localization::Language (enum order). Wording is the game\'s exact', '// per-language text, not a translation.',
           '#pragma once', '', '#include <string_view>', '', 'namespace LocalizationData', '{',
           '\tconstexpr int kCategoryCount = 9;',
           '\t// Category enum order: Bandit, Explorer, Gambler, Herbalist, Horseman, Master Hunter,',
           '\t// Sharpshooter, Survivalist, Weapons Expert', '\tconstexpr std::string_view kCategoryNames[13][kCategoryCount] =', '\t{']
    for n, code in ORDER:
        names = [lookup(blobs[n], d.joaat(l)) for l in CATEGORY_LABELS]
        out.append('\t\t{ ' + ', '.join(cstr(x) for x in names) + ' }, // ' + code)
    out += ['\t};', '', '\t// Objective text: [language][category][rank - 1] (the game\'s rankDescLabel).',
            '\tconstexpr std::string_view kRankObjectives[13][kCategoryCount][10] =', '\t{']
    ranks = rank_labels()
    for n, code in ORDER:
        out.append('\t\t{ // ' + code)
        for cat in ranks:
            out.append('\t\t\t{ ' + ', '.join(cstr(lookup(blobs[n], d.joaat(l))) for l in cat) + ' },')
        out.append('\t\t},')
    out += ['\t};', '', '\t// The game\'s own term for the Dead Eye ability.','\tconstexpr std::string_view kDeadEye[13] =', '\t{']
    for n, code in ORDER:
        out.append('\t\t' + cstr(lookup(blobs[n], DEADEYE_HASH)) + ', // ' + code)
    out += ['\t};', '}', '']
    Path(__file__).parent.parent.joinpath('src', 'LocalizationData.h').write_bytes('\r\n'.join(out).encode('utf-8'))
    print('ok')

if __name__ == '__main__': main()
