/*
	ChallengeCheat -- research trail and current coverage.

	GOAL: advance/complete RDR2's 9 singleplayer "Challenges" (Bandit,
	Explorer, Gambler, Herbalist, Horseman, Master Hunter, Sharpshooter,
	Survivalist, Weapons Expert) through the game's own real progress
	system, so that whatever reward-grant logic normally reacts to a
	completed rank still fires.

	NATIVE SURFACE (external\ScriptHookSDK\inc\natives.h):
	  STATS::CHAL_GET_NUM_RANKS_COMPLETED(Hash chalHash) -> int
	  STATS::CHAL_GET_MAX_RANKS(Hash chalHash) -> int
	  STATS::CHAL_SET_GOAL_PROGRESS_INT(Hash chalHash, Hash goalHash, int value)
	  STATS::STAT_ID_SET_INT(StatId* statId, int value, BOOL p2) -> BOOL
	  STATS::STAT_ID_SET_FLOAT(StatId* statId, float value, BOOL p2) -> BOOL
	  StatId is a documented struct right above STAT_ID_IS_VALID in
	  natives.h: { alignas(8) Hash BaseId; alignas(8) Hash PermutationId; }

	ROOT HASHES: confirmed directly from
	D:\Backup\Stuff\RDR2 Shit\Scripts\1491.50\script_rel\pause_menu.ysc.c's
	own index -> hash switch (~line 7147) -- see kCategoryInfo below.

	THE REAL GOAL REGISTRY -- and a live-fire lesson learned the hard way
	(2026-09-17): the user first extracted `challenges_sp.meta`/
	`goals_sp.meta` from disk and handed them over, and an earlier version
	of this file was built entirely against them, using
	CHAL_SET_GOAL_PROGRESS_INT(chalHash, joaat(goalName), desiredGoal) --
	the goal's own name, taken as a literal goalHash -- as a UNIVERSAL
	mechanism for every goal regardless of how it's normally tracked. That
	shipped, built clean, and failed live: 3 for 3 AdvanceRank attempts
	(Bandit rank 2, Explorer rank 5, Gambler rank 6) applied without error
	but never moved CHAL_GET_NUM_RANKS_COMPLETED. Digging into WHY
	revealed the real problem: those two files were not vanilla data at
	all -- their header comment admitted as much ("Gambler #2-10 auto
	complete") -- someone had already rewritten several goals' `scoreParam`
	to point at unrelated, trivially-satisfiable stats (e.g. Gambler rank
	6's "win blackjack at Rhodes" goal had been rewired to just check
	TOTAL_PLAYING_GAME_TIME >= 10). The user correctly called this
	"BS from a mod" and had the real files pulled directly from the game's
	own RPFs instead (`RDR2-RPF-Tool`, headless CLI mode added to it this
	session specifically for this -- see that tool's own HeadlessQuery.cs/
	RPF8.cs for the read-only load path added so it can run while RDR2.exe
	has the RPF open). The real files live in `update_1.rpf` at
	`common/data/stats_and_challenges/{goals,challenges}_sp.meta` -- NOT
	in the base `data_0.rpf`, and NOT in the later update_2/3/4.rpf either
	(this specific path apparently hasn't needed re-patching since
	update_1). Both real files are archived at
	`D:\Backup\Stuff\RDR2 Shit\{goals,challenges}_sp.meta` (the fake ones
	are kept alongside as `*_FAKE_MOD.meta` for reference/comparison, not
	used by anything).

	Against the REAL data, the picture is meaningfully different: only 10
	of 138 goals are genuinely `StatsGoalScoreSourceScript`-sourced (up
	from the fake file's 2, but still a small minority) -- these are the
	only goals `CHAL_SET_GOAL_PROGRESS_INT`-by-name is actually the
	correct, real mechanism for (it's literally what the vanilla game
	itself would call for them). The other 102 non-unsupported goals are
	genuinely `StatsGoalScoreSourceStat`-sourced, each naming a real,
	sane-looking stat (`KILLED`/`AT_RABBIT`, `LONGEST_DIST_DRAGGED`,
	`HOLD_UPS_IN_TOWN`, etc. -- these line up exactly with the plain-
	English challenge descriptions the user separately supplied, e.g.
	Horseman rank 4's `LONGEST_DIST_DRAGGED=1006` for "drag a victim
	3,300 feet"). Since the live test already showed writing the GOAL's
	own progress counter does NOT retroactively satisfy a stat-sourced
	goal's real completion check, this version writes the REAL underlying
	stat(s) directly instead, via `STATS::STAT_ID_SET_INT`/
	`STAT_ID_SET_FLOAT` -- the same mechanism `dominoes_sp.ysc.c`'s own
	`func_940` uses for a real stat write (`STAT_ID_SET_INT(&statId,
	value, true)`), just parameterized from the real per-goal data instead
	of a single hardcoded stat.

	`kKnownWrites` below (217 rows, including 9 hand-added HorseCompendium
	rows for Horseman rank 10 -- see that section's own comment) was
	generated by parsing both real
	meta files with Python (`xml.etree.ElementTree`): `challenges_sp.meta`
	gives every rank's real goal name(s) in order; `goals_sp.meta`'s
	`<scoreParam>` tree is walked recursively per goal, descending through
	wrapper types (`AIConditional`/`Binding`/`Resetable`/`IntSum`/
	`IntGroupSum`) to find every leaf `StatsGoalScoreSourceStat` (emitting
	one write row per leaf, at the nearest enclosing `desiredGoal` -- a sum
	goal's every contributing stat gets pushed to the FULL combined target,
	a safe overshoot for a "sum >= N" check) or the single
	`StatsGoalScoreSourceScript` `<id>` (emitting one ScriptGoal row).…
	Goals whose only source is a compendium entry, a "collect N of this
	item list" group, a "reach threshold on N different stats in a named
	group" group, or (3 Horseman ranks) no `<scoreParam>` at all (a
	location-to-location timed ride, evaluated live, not from a persisted
	number) are NOT in the table -- see the coverage table in CLAUDE.md.

	CURRENT COVERAGE: every rank of Bandit, Gambler, Survivalist, and
	Weapons Expert (all 1-10). Explorer/Sharpshooter/Master Hunter/
	Herbalist/Horseman each hit a real ceiling at a specific rank whose
	ONLY goal has no known mechanism at all yet -- see CLAUDE.md's table.
	`AdvanceRank()` never claims success on a guess: it independently
	re-reads `CHAL_GET_NUM_RANKS_COMPLETED` after writing and only reports
	success if the counter actually moved.

	STILL UNVERIFIED (this rewrite has not been live-tested yet): whether
	directly overwriting the named stat itself moves the rank counter, and
	whether it triggers real reward-grant. This is a much stronger bet
	than the disproven goal-name-write theory (it's exactly what a
	legitimate playthrough would have written), but it's still a claim
	that needs a real test, not an assumption.

	HORSEMAN RANKS 3/6/9 (the 3 StatsGoalPointToPoint "timed ride" goals,
	no <scoreParam>, no script or documented native anywhere near them --
	see this file's own coverage notes and CLAUDE.md): CONFIRMED LIVE
	2026-09-17 that the completion check itself is `sub_140BAC640` in the
	analyzed build (RDR2.exe+0xBAC640), found by planting a distinctive
	marker value (durationSeconds 300 -> 13371337) via an LML-overridden
	goals_sp.meta and using Cheat Engine's "find out what accesses this
	address" on it.

	A first fix patched one internal conditional jump to force the
	function's own null-tracking-context fallback path unconditionally --
	live-confirmed to complete Horseman rank 3, but with a bug: advancing
	rank 3 also silently completed ranks 6 and 9 later, with no hook ever
	installed for them specifically. A logging-only MinHook detour (zero
	effect on behavior, just observed arguments) explained why:
	sub_140BAC640 is called once per PointToPoint goal INSTANCE during a
	single shared periodic re-evaluation pass -- three calls observed
	back-to-back in the very same tick, one per goal, each with a
	different `a1` and, critically, a different RDX value (0x161/0x164/
	0x167 for ranks 3/6/9 respectively, consistently spaced by 3 -- a
	per-goal index). The old unconditional patch had no way to tell these
	apart, so it forced success for whichever goal(s) happened to be
	evaluated during its brief patch window -- not always just the one
	requested.

	`WriteKind::PointToPointHook` below now uses a real MinHook detour
	(TimedRideHook.h/.cpp) that inspects RDX and only forces the fallback
	path (`return (char)sub_140B9842C(a1)`, exactly replicating the
	original function's own behavior for an untracked goal) when RDX
	matches the SPECIFIC goal being targeted -- every other call (any
	other RDX) passes straight through to the real evaluation, completely
	unaffected. The hook is enabled for the targeted AdvanceRank() attempt
	and disables itself immediately after the first matching RDX calls the
	unlock/fallback function, so it does not remain hooked for the rest of
	the poll window once the intended goal has fired.
*/

#include "ChallengeCheat.h"
#include "Log.h"
#include "script.h"
#include "TimedRideHook.h"

#include "..\external\RDR-Classes\rage\joaat.hpp"

#include <cstddef>
#include <optional>

namespace
{
	using ChallengeCheat::Category;

	// Documented in natives.h directly above STAT_ID_IS_VALID:
	//   struct StatId { alignas(8) Hash BaseId; alignas(8) Hash PermutationId; }
	struct StatId
	{
		alignas(8) Hash BaseId;
		alignas(8) Hash PermutationId;
	};

	struct CategoryInfo
	{
		const char* displayName;
		const char* rootHashName;
	};

	// Order matches Category's enum order, which matches pause_menu.ysc.c's
	// own index switch exactly (see this file's header comment).
	constexpr CategoryInfo kCategoryInfo[] = {
		{ "Bandit",         "sp_chal_band_root" },
		{ "Explorer",       "sp_chal_expl_root" },
		{ "Gambler",        "sp_chal_gamb_root" },
		{ "Herbalist",      "sp_chal_herb_root" },
		{ "Horseman",       "sp_chal_horse_root" },
		{ "Master Hunter",  "sp_chal_hunt_root" },
		{ "Sharpshooter",   "sp_chal_shot_root" },
		{ "Survivalist",    "sp_chal_surv_root" },
		{ "Weapons Expert", "sp_chal_weap_root" },
	};

	const CategoryInfo& Info(Category category)
	{
		return kCategoryInfo[static_cast<std::size_t>(category)];
	}

	Hash RootHash(Category category)
	{
		return static_cast<Hash>(rage::Joaat(Info(category).rootHashName));
	}

	enum class WriteKind
	{
		Stat,            // write baseId/permId's real named stat directly
		ScriptGoal,      // write the goal's own name via CHAL_ADD_GOAL_PROGRESS_INT
		PointToPointHook, // scoped binary patch of the native completion check -- see TimedRideHook.h
		HorseCompendium, // spawn modelHash's breed ped, call COMPENDIUM_HORSE_WILD_BROKEN, delete it
	};

	// A handful of real goals wrap their scoreParam in a
	// StatsGoalParamAIConditional -- live-CONFIRMED (2026-09-17, Horseman
	// rank 1) that this is a real runtime gate checked at evaluation time,
	// not just a description of how the stat normally accumulates during
	// real play: writing the stat directly did nothing until the player
	// was actually on horseback when the write happened. Found by scanning
	// every goal in goals_sp.meta for an AIConditional wrapper's
	// <condition type="...">, not just the one that failed live.
	enum class Requirement
	{
		None,
		OnMount,       // CAIConditionIsOnMount -- checked live via PED::IS_PED_ON_MOUNT
		OnMovingTrain, // CAIConditionGoalContext (CHAL_CTX_ON_MOVING_TRAIN) -- no native check found yet, logged as a note only
		DeadeyeActive, // CAIConditionPlayerIsDeadeyeActive -- no native check found yet, logged as a note only
	};

	struct KnownWrite
	{
		Category category;
		int rank; // 1-indexed: this write contributes to reaching this rank
		WriteKind kind;
		const char* label;  // goal name -- always the goal's real <name>, for logging
		const char* baseId; // Stat only: statId BaseId ("" if this stat has none)
		const char* permId; // Stat only: statId PermutationId ("" if none)
		float value;
		bool isFloat; // Stat: increment as float vs int. ScriptGoal: always false (int goals only so far)
		Requirement requirement = Requirement::None;
		Hash modelHash = 0; // HorseCompendium only: the breed's ped model hash
	};

	// Auto-generated from the REAL challenges_sp.meta + goals_sp.meta
	// (extracted from update_1.rpf, NOT the fake mod copy -- see this
	// file's header comment). 217 write rows covering 121 of 138 goals
	// (112 auto-generated Stat/ScriptGoal/PointToPointHook rows, plus 9
	// hand-added HorseCompendium rows for Horseman rank 10 -- see below).
	constexpr KnownWrite kKnownWrites[] = {
		{ Category::Bandit, 1, WriteKind::Stat, "ACW_BAND_Rank_01_Townsfolk", "HOLD_UPS_IN_TOWN", "", 5.000000f, false },
		{ Category::Bandit, 2, WriteKind::Stat, "ACW_BAND_Rank_02_CoachRobberies", "", "AMBIENT_COACH_ROBBED", 2.000000f, false },
		{ Category::Bandit, 2, WriteKind::Stat, "ACW_BAND_Rank_02_CoachRobberies", "STOLEN_WAGONS_SOLD", "", 2.000000f, false },
		{ Category::Bandit, 3, WriteKind::Stat, "ACW_BAND_Rank_03_ShopRobberies", "CASH_REGISTERS_ROBBED", "", 4.000000f, false },
		{ Category::Bandit, 4, WriteKind::Stat, "ACW_BAND_Rank_04_CoachesRobbedInADay", "", "AMBIENT_COACH_ROBBED", 3.000000f, false },
		{ Category::Bandit, 4, WriteKind::Stat, "ACW_BAND_Rank_04_CoachesRobbedInADay", "STOLEN_WAGONS_SOLD", "", 3.000000f, false },
		{ Category::Bandit, 5, WriteKind::Stat, "ACW_BAND_Rank_05_HighestBounty", "HIGHEST_BOUNTY", "", 25000.000000f, false },
		{ Category::Bandit, 6, WriteKind::Stat, "ACW_BAND_Rank_06_HorsesFenced", "STOLEN_HORSES_SOLD", "", 5.000000f, false },
		{ Category::Bandit, 7, WriteKind::Stat, "ACW_BAND_Rank_07_StealCash", "HOLD_UP_CASH", "CIVILIAN", 5000.000000f, false },
		{ Category::Bandit, 8, WriteKind::Stat, "ACW_BAND_Rank_08_WagonsFenced", "STOLEN_WAGONS_SOLD", "", 7.000000f, false },
		{ Category::Bandit, 9, WriteKind::Stat, "ACW_BAND_Rank_09_HogtiedTrainTracks", "TIMES_HOGTIED_ONTO_TRAIN_TRACKS", "", 3.000000f, false },
		{ Category::Bandit, 10, WriteKind::Stat, "ACW_BAND_Rank_10_TrainRobberies", "ROB_COMPLETED", "TRAIN", 5.000000f, false },
		{ Category::Explorer, 1, WriteKind::ScriptGoal, "ACW_EXPL_Rank_01_Treasure", "", "", 1.000000f, false },
		{ Category::Gambler, 1, WriteKind::Stat, "ACW_GAMB_Rank_01_Poker", "WINS", "POKER_HAND", 5.000000f, false },
		{ Category::Gambler, 2, WriteKind::Stat, "ACW_GAMB_Rank_02_Blackjack", "WINS", "BLACKJACK_DOUBLED_DOWN", 5.000000f, false },
		{ Category::Gambler, 3, WriteKind::Stat, "ACW_GAMB_Rank_03_FiveFingerFillet", "WINS", "FIVE_FINGER", 3.000000f, false },
		{ Category::Gambler, 4, WriteKind::ScriptGoal, "ACW_GAMB_Rank_04_Poker_FNS", "", "", 1.000000f, false },
		{ Category::Gambler, 4, WriteKind::ScriptGoal, "ACW_GAMB_Rank_04_Poker_SDN", "", "", 1.000000f, false },
		{ Category::Gambler, 4, WriteKind::ScriptGoal, "ACW_GAMB_Rank_04_Poker_VAL", "", "", 1.000000f, false },
		{ Category::Gambler, 5, WriteKind::Stat, "ACW_GAMB_Rank_05_Dominoes", "WINS", "DOMINOES_NO_DRAWS", 3.000000f, false },
		{ Category::Gambler, 6, WriteKind::ScriptGoal, "ACW_GAMB_Rank_06_Blackjack_RHO", "", "", 1.000000f, false },
		{ Category::Gambler, 6, WriteKind::ScriptGoal, "ACW_GAMB_Rank_06_Blackjack_VAN", "", "", 1.000000f, false },
		{ Category::Gambler, 7, WriteKind::ScriptGoal, "ACW_GAMB_Rank_07_FiveFinger_STR", "", "", 1.000000f, false },
		{ Category::Gambler, 7, WriteKind::ScriptGoal, "ACW_GAMB_Rank_07_FiveFinger_VAL", "", "", 1.000000f, false },
		{ Category::Gambler, 7, WriteKind::ScriptGoal, "ACW_GAMB_Rank_07_FiveFinger_VAN", "", "", 1.000000f, false },
		{ Category::Gambler, 8, WriteKind::Stat, "ACW_GAMB_Rank_08_Blackjack", "WINS", "BLACKJACK_4_HITS", 3.000000f, false },
		{ Category::Gambler, 9, WriteKind::Stat, "ACW_GAMB_Rank_09_Dominoes", "WIN_STREAK", "DOMINOES_GAME", 3.000000f, false },
		{ Category::Gambler, 10, WriteKind::Stat, "ACW_GAMB_Rank_10_PokerHands", "WIN_STREAK", "POKER_HAND", 3.000000f, false },
		{ Category::Herbalist, 1, WriteKind::Stat, "ACW_HERB_Rank_01_Yarrow", "PICK", "HERB_YARROW", 6.000000f, false },
		{ Category::Herbalist, 2, WriteKind::Stat, "ACW_HERB_Rank_02_Berries", "EATEN", "HERB_BLACK_BERRY", 1.000000f, false },
		{ Category::Herbalist, 2, WriteKind::Stat, "ACW_HERB_Rank_02_Berries", "EATEN", "HERB_EVERGREEN_HUCKLEBERRY", 1.000000f, false },
		{ Category::Herbalist, 2, WriteKind::Stat, "ACW_HERB_Rank_02_Berries", "EATEN", "HERB_RED_RASPBERRY", 1.000000f, false },
		{ Category::Herbalist, 2, WriteKind::Stat, "ACW_HERB_Rank_02_Berries", "EATEN", "HERB_WINTERGREEN_BERRY", 1.000000f, false },
		{ Category::Herbalist, 3, WriteKind::Stat, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_POTENT_HORSE_STIMULANT", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::Stat, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_SPECIAL_HORSE_STIMULANT_CRAFTED", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::Stat, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_HORSE_OINTMENT_CRAFTED", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::Stat, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_POTENT_RESTORATIVE", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::Stat, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_SPECIAL_RESTORATIVE_CRAFTED", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::Stat, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_POTENT_TONIC", 7.000000f, false },
		{ Category::Herbalist, 4, WriteKind::Stat, "ACW_HERB_Rank_04_FeedMushrooms", "", "HORSE_FED_MUSHROOM", 5.000000f, false },
		{ Category::Herbalist, 5, WriteKind::Stat, "ACW_HERB_Rank_05_TobaccoCrafting", "MADE", "CONSUMABLE_POTENT_SNAKE_OIL", 9.000000f, false },
		{ Category::Herbalist, 5, WriteKind::Stat, "ACW_HERB_Rank_05_TobaccoCrafting", "MADE", "CONSUMABLE_SPECIAL_SNAKE_OIL_CRAFTED", 9.000000f, false },
		{ Category::Herbalist, 5, WriteKind::Stat, "ACW_HERB_Rank_05_TobaccoCrafting", "MADE", "CONSUMABLE_POTENT_TONIC", 9.000000f, false },
		{ Category::Herbalist, 7, WriteKind::Stat, "ACW_HERB_Rank_07_CraftSpecialTonic", "MADE", "CONSUMABLE_SPECIAL_TONIC_CRAFTED", 5.000000f, false },
		{ Category::Herbalist, 7, WriteKind::Stat, "ACW_HERB_Rank_07_UseSpecialTonic", "USED", "SPECIAL_TONIC", 5.000000f, false },
		{ Category::Herbalist, 8, WriteKind::Stat, "ACW_HERB_Rank_08_PoisonWeapons", "MADE", "AMMO_ARROW_POISON", 6.000000f, false },
		{ Category::Herbalist, 8, WriteKind::Stat, "ACW_HERB_Rank_08_PoisonWeapons", "MADE", "AMMO_THROWING_KNIVES_POISON", 6.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_ExoticBirdSeasoning", "COOKED", "CONSUMABLE_EXOTIC_BIRD_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_ExoticBirdSeasoning", "COOKED", "CONSUMABLE_EXOTIC_BIRD_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_ExoticBirdSeasoning", "COOKED", "CONSUMABLE_EXOTIC_BIRD_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_TenderPorkSeasoning", "COOKED", "CONSUMABLE_TENDER_PORK_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_TenderPorkSeasoning", "COOKED", "CONSUMABLE_TENDER_PORK_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_TenderPorkSeasoning", "COOKED", "CONSUMABLE_TENDER_PORK_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_PlumpBirdSeasoning", "COOKED", "CONSUMABLE_PLUMP_BIRD_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_PlumpBirdSeasoning", "COOKED", "CONSUMABLE_PLUMP_BIRD_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_PlumpBirdSeasoning", "COOKED", "CONSUMABLE_PLUMP_BIRD_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_BigGameMeatSeasoning", "COOKED", "CONSUMABLE_BIG_GAME_MEAT_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_BigGameMeatSeasoning", "COOKED", "CONSUMABLE_BIG_GAME_MEAT_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_BigGameMeatSeasoning", "COOKED", "CONSUMABLE_BIG_GAME_MEAT_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_PrimeBeefSeasoning", "COOKED", "CONSUMABLE_PRIME_BEEF_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_PrimeBeefSeasoning", "COOKED", "CONSUMABLE_PRIME_BEEF_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_PrimeBeefSeasoning", "COOKED", "CONSUMABLE_PRIME_BEEF_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_SucculentFishSeasoning", "COOKED", "CONSUMABLE_SUCCULENT_FISH_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_SucculentFishSeasoning", "COOKED", "CONSUMABLE_SUCCULENT_FISH_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_SucculentFishSeasoning", "COOKED", "CONSUMABLE_SUCCULENT_FISH_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_GameMeatSeasoning", "COOKED", "CONSUMABLE_GAME_MEAT_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_GameMeatSeasoning", "COOKED", "CONSUMABLE_GAME_MEAT_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_GameMeatSeasoning", "COOKED", "CONSUMABLE_GAME_MEAT_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_FlakeyFishSeasoning", "COOKED", "CONSUMABLE_FLAKEY_FISH_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_FlakeyFishSeasoning", "COOKED", "CONSUMABLE_FLAKEY_FISH_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_FlakeyFishSeasoning", "COOKED", "CONSUMABLE_FLAKEY_FISH_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_CrustaceanMeatSeasoning", "COOKED", "CONSUMABLE_CRUSTACEAN_MEAT_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_CrustaceanMeatSeasoning", "COOKED", "CONSUMABLE_CRUSTACEAN_MEAT_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_CrustaceanMeatSeasoning", "COOKED", "CONSUMABLE_CRUSTACEAN_MEAT_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_GristlyMuttonSeasoning", "COOKED", "CONSUMABLE_GRISTLY_MUTTON_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_GristlyMuttonSeasoning", "COOKED", "CONSUMABLE_GRISTLY_MUTTON_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_GristlyMuttonSeasoning", "COOKED", "CONSUMABLE_GRISTLY_MUTTON_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_MatureVenisonSeasoning", "COOKED", "CONSUMABLE_MATURE_VENISON_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_MatureVenisonSeasoning", "COOKED", "CONSUMABLE_MATURE_VENISON_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::Stat, "ACW_HERB_Rank_10_MatureVenisonSeasoning", "COOKED", "CONSUMABLE_MATURE_VENISON_THYME_COOKED", 1.000000f, false },
		{ Category::Horseman, 1, WriteKind::Stat, "ACW_HORSE_Rank_01_Rabbits", "KILLED", "AT_RABBIT", 5.000000f, false, Requirement::OnMount },
		{ Category::Horseman, 2, WriteKind::Stat, "ACW_HORSE_Rank_02_Obstacles", "", "HORSE_VAULTS", 3.000000f, false },
		// Ranks 3/6/9 (ACW_HORSE_Rank_{03,06,09}_TimedRide) are
		// StatsGoalPointToPoint goals -- no <scoreParam> at all in
		// goals_sp.meta, and no script anywhere references these goal
		// names, "PointToPoint"/"TimedRide", or either region volume
		// (checked all 1,638 decompiled SP scripts). Every documented
		// native/goal-progress lever was tried and disproven (see this
		// file's header comment). CONFIRMED LIVE 2026-09-17: the real
		// completion check is a native function (sub_140BAC640 in the
		// analyzed build), and the specific goal it's evaluating on any
		// given call is identified by RDX -- WriteKind::PointToPointHook
		// rows store that timed-ride goal index in `value` (reusing the same
		// field other WriteKinds use differently, per KnownWrite's own
		// comment) so TimedRideHook::ScopedTimedRideUnlock can target exactly one
		// goal instead of affecting whichever ones happen to be evaluated
		// in the same tick -- see TimedRideHook.h/.cpp.
		{ Category::Horseman, 3, WriteKind::PointToPointHook, "ACW_HORSE_Rank_03_TimedRide", "", "", 353.000000f, false }, // rdx 0x161
		{ Category::Horseman, 4, WriteKind::Stat, "ACW_HORSE_Rank_04_LassoDrag", "LONGEST_DIST_DRAGGED", "", 1006.000000f, true, Requirement::OnMount },
		{ Category::Horseman, 5, WriteKind::Stat, "ACW_HORSE_Rank_05_Trample", "KILLS", "ANIMAL", 5.000000f, false },
		{ Category::Horseman, 5, WriteKind::Stat, "ACW_HORSE_Rank_05_Trample", "KILLS", "TRAMPLE", 1.000000f, false },
		{ Category::Horseman, 6, WriteKind::PointToPointHook, "ACW_HORSE_Rank_06_TimedRide", "", "", 356.000000f, false }, // rdx 0x164
		{ Category::Horseman, 7, WriteKind::Stat, "ACW_HORSE_Rank_07_KillNoDismount", "KILLS", "ENEMY", 7.000000f, false, Requirement::OnMount },
		{ Category::Horseman, 8, WriteKind::Stat, "ACW_HORSE_Rank_08_Predators", "KILLS", "PREDATOR", 9.000000f, false, Requirement::OnMount },
		{ Category::Horseman, 9, WriteKind::PointToPointHook, "ACW_HORSE_Rank_09_TimedRide", "", "", 359.000000f, false }, // rdx 0x167
		// Rank 10 requires ALL 9 of these goals (challenges_sp.meta lists
		// them together under one rank's <goalHashes>, not as alternatives --
		// Arabian is commented out in the real file, so only 9 breeds are
		// actually required). Each goal's only scoreParam leaf is a
		// StatsGoalScoreSourceCompendium (e.g. CMPNDM_AMPAINT/_RARE for the
		// Paint goal), which kKnownWrites' generator never emitted a row for
		// (Stat/Script leaves only) -- see this file's header comment and
		// CLAUDE.md's coverage table. Fixed 2026-09-18: the real script
		// (player_horse.ysc.c) marks a breed's compendium entry "broken" by
		// calling COMPENDIUM::COMPENDIUM_HORSE_WILD_BROKEN(pedIndex) on the
		// wild horse ped just tamed -- the native reads the ped's own model
		// to figure out which breed/entry to credit, so WriteKind::HorseCompendium
		// spawns a short-lived ped of each breed's model, calls the native on
		// it, then deletes it. modelHash values are the real breed ped model
		// hashes (not joaat of the English breed name -- verified those don't
		// match; these came from the user's own data pull).
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_American_Paint", "", "", 0.0f, false, Requirement::None, 0xE52CB9B2 },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_American_Standardbred", "", "", 0.0f, false, Requirement::None, 0xED07737A },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Appaloosa", "", "", 0.0f, false, Requirement::None, 0x7EF6A7DC },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Hungarian", "", "", 0.0f, false, Requirement::None, 0x65A30467 },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Kentucky", "", "", 0.0f, false, Requirement::None, 0xA5A0532E },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Morgan", "", "", 0.0f, false, Requirement::None, 0x4955CBE3 },
		// modelHash here is a_c_horse_mustang_wildbay, NOT the earlier
		// A_C_HORSE_MUSTANG_BUCKSKIN (0x62121AEC) -- live-tested 2026-09-1{8,9}
		// and DISPROVEN: the native ran without error (log line printed) but
		// never actually marked CMPNDM_MUSTANG/_RARE broken. Buckskin never
		// once appears among the wild-population coat switch cases any
		// decompiled SP script uses for Mustang (grullodun/tigerstripedbay/
		// goldendun/wildbay are the only 4 -- confirmed by grepping all 1,638
		// scripts) -- it's a stable-purchase-only coat, not one the ambient
		// wild population (or COMPENDIUM_HORSE_WILD_BROKEN's own internal
		// wild-coat table) recognizes as a legitimate "wild" Mustang. Picked
		// wildbay (appears as the sole/default case in several scripts,
		// e.g. ambush_bnd_cliff1.ysc.c) as a real wild coat instead.
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Mustang", "", "", 0.0f, false, Requirement::None, 0x7E4DF66E },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Nokota", "", "", 0.0f, false, Requirement::None, 0x0660E640 },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Tennessee", "", "", 0.0f, false, Requirement::None, 0x400B3937 },
		{ Category::MasterHunter, 1, WriteKind::Stat, "ACW_HUNT_Rank_01_Skin", "SKINNED", "AT_DEER", 3.000000f, false },
		{ Category::MasterHunter, 1, WriteKind::Stat, "ACW_HUNT_Rank_01_Skin", "SKINNED", "AT_BUCK", 3.000000f, false },
		{ Category::MasterHunter, 1, WriteKind::Stat, "ACW_HUNT_Rank_01_Skin", "SKINNED", "AT_BUCK_LEGENDARY", 3.000000f, false },
		{ Category::MasterHunter, 2, WriteKind::ScriptGoal, "ACW_HUNT_Rank_02_Rabbits", "", "", 3.000000f, false },
		{ Category::MasterHunter, 4, WriteKind::Stat, "ACW_HUNT_Rank_04_CleanKill", "KILLS", "ANIMAL_RESPONDING_TO_CALL", 5.000000f, false },
		{ Category::MasterHunter, 5, WriteKind::Stat, "ACW_HUNT_Rank_05_Bear", "SKINNED", "AT_BEAR_GRIZZLY", 3.000000f, false },
		{ Category::MasterHunter, 5, WriteKind::Stat, "ACW_HUNT_Rank_05_Bear", "SKINNED", "AT_BEAR_LEGENDARY", 3.000000f, false },
		{ Category::MasterHunter, 5, WriteKind::Stat, "ACW_HUNT_Rank_05_Bear", "SKINNED", "AT_BEAR_BLACK", 3.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::Stat, "ACW_HUNT_Rank_06_CougarKill", "KILLED", "AT_COUGAR", 5.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::Stat, "ACW_HUNT_Rank_06_CougarKill", "KILLED", "AT_COUGAR_LEGENDARY", 5.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::Stat, "ACW_HUNT_Rank_06_CougarKill", "KILLS", "SN_BOW", 1.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::Stat, "ACW_HUNT_Rank_06_CougarSkin", "SKINNED", "AT_COUGAR", 5.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::Stat, "ACW_HUNT_Rank_06_CougarSkin", "SKINNED", "AT_COUGAR_LEGENDARY", 5.000000f, false },
		{ Category::MasterHunter, 7, WriteKind::Stat, "ACW_HUNT_Rank_07_BaitedKills", "KILLS", "ANIMAL_HERBIVORE_BAITED", 1.000000f, false },
		{ Category::MasterHunter, 7, WriteKind::Stat, "ACW_HUNT_Rank_07_BaitedKills", "KILLS", "ANIMAL_PREDATOR_BAITED", 1.000000f, false },
		{ Category::MasterHunter, 8, WriteKind::Stat, "ACW_HUNT_Rank_08_LootedFish", "LOOTED", "FISH", 3.000000f, false },
		{ Category::MasterHunter, 9, WriteKind::Stat, "ACW_HUNT_Rank_09_Possum", "KILLED_WHILST_PLAYING_DEAD", "AT_POSSUM", 1.000000f, false },
		{ Category::MasterHunter, 10, WriteKind::Stat, "ACW_HUNT_Rank_10_Panther", "KILLED", "AT_PANTHER_LEGENDARY", 1.000000f, false },
		{ Category::Sharpshooter, 1, WriteKind::Stat, "ACW_SHOT_Rank_01_Flying", "KILLS", "FLYING_BIRD", 3.000000f, false },
		{ Category::Sharpshooter, 1, WriteKind::Stat, "ACW_SHOT_Rank_01_Flying", "KILLED", "AT_BAT", 1.000000f, false },
		{ Category::Sharpshooter, 1, WriteKind::Stat, "ACW_SHOT_Rank_01_Flying", "KILLS", "SHOOTING", 1.000000f, false },
		{ Category::Sharpshooter, 3, WriteKind::Stat, "ACW_SHOT_Rank_03_Train", "KILLS", "FLYING_BIRD", 5.000000f, false, Requirement::OnMovingTrain },
		{ Category::Sharpshooter, 3, WriteKind::Stat, "ACW_SHOT_Rank_03_Train", "KILLED", "AT_BAT", 1.000000f, false, Requirement::OnMovingTrain },
		{ Category::Sharpshooter, 4, WriteKind::Stat, "ACW_SHOT_Rank_04_Tomahawk", "FURTHEST_KILL", "TH_TOMAHAWK", 24.500000f, true },
		{ Category::Sharpshooter, 4, WriteKind::Stat, "ACW_SHOT_Rank_04_Tomahawk", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::Sharpshooter, 5, WriteKind::Stat, "ACW_SHOT_Rank_05_Switching", "KILLS", "ANIMAL", 6.000000f, false },
		{ Category::Sharpshooter, 5, WriteKind::Stat, "ACW_SHOT_Rank_05_Switching", "KILLS", "GUN", 1.000000f, false },
		{ Category::Sharpshooter, 6, WriteKind::Stat, "ACW_SHOT_Rank_06_ScopedRifle", "FURTHEST_KILL", "", 201.199997f, true },
		{ Category::Sharpshooter, 6, WriteKind::Stat, "ACW_SHOT_Rank_06_ScopedRifle", "KILLS", "GROUP_SNIPER", 1.000000f, false },
		{ Category::Sharpshooter, 6, WriteKind::Stat, "ACW_SHOT_Rank_06_ScopedRifle", "KILLS", "HUMAN", 1.000000f, false },
		{ Category::Sharpshooter, 7, WriteKind::Stat, "ACW_SHOT_Rank_07_Headshots", "STREAK", "HEADSHOT", 7.000000f, false },
		{ Category::Sharpshooter, 8, WriteKind::Stat, "ACW_SHOT_Rank_08_Disarm", "DISARMS", "", 3.000000f, false },
		{ Category::Sharpshooter, 9, WriteKind::Stat, "ACW_SHOT_Rank_09_Disarm", "HATSHOTS", "", 3.000000f, false, Requirement::DeadeyeActive },
		{ Category::Sharpshooter, 10, WriteKind::Stat, "ACW_SHOT_Rank_10_SniperRifle", "KILLS", "FLYING_BIRD", 3.000000f, false },
		{ Category::Sharpshooter, 10, WriteKind::Stat, "ACW_SHOT_Rank_10_SniperRifle", "KILLS", "GROUP_SNIPER", 1.000000f, false },
		{ Category::Survivalist, 1, WriteKind::Stat, "ACW_SURV_Rank_01_Bluegill", "CAUGHT", "AT_FBLUEGIL", 3.000000f, false },
		{ Category::Survivalist, 1, WriteKind::Stat, "ACW_SURV_Rank_01_Bluegill", "CAUGHT", "AT_FBLUEGILL_LEGENDARY", 3.000000f, false },
		{ Category::Survivalist, 2, WriteKind::Stat, "ACW_SURV_Rank_02_CarcassDonation", "CARCASSES_DONATED", "", 5.000000f, false },
		{ Category::Survivalist, 3, WriteKind::Stat, "ACW_SURV_Rank_03_VarmintRifle", "KILLS", "RF_VARMINT", 5.000000f, false },
		{ Category::Survivalist, 3, WriteKind::Stat, "ACW_SURV_Rank_03_VarmintRifle", "KILLS", "ANIMAL", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_DynamiteArrow", "MADE", "AMMO_ARROW_DYNAMITE", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_FireArrow", "MADE", "AMMO_ARROW_FIRE", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_ImprovedArrow", "MADE", "AMMO_ARROW_IMPROVED", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_PoisonArrow", "MADE", "AMMO_ARROW_POISON", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_SmallGameArrow", "MADE", "AMMO_ARROW_SMALL_GAME", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "CANOE", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "PIROGUE", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "ROWBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "ROWBOATSWAMP", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "SKIFF", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "GUAMABOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "HORSEBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "KEELBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "RCBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "STEAMBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "TUGBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "TURBINEBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingTracks", "FISH_CAUGHT_ON_TRAIN_TRACKS", "", 1.000000f, false },
		{ Category::Survivalist, 6, WriteKind::Stat, "ACW_SURV_Rank_06_ScavengerKill", "KILLS", "SCAVENGING_ANIMAL", 5.000000f, false },
		{ Category::Survivalist, 7, WriteKind::Stat, "ACW_SURV_Rank_07_SmallGame", "KILLS", "SMALL_ANIMALS", 8.000000f, false },
		{ Category::Survivalist, 7, WriteKind::Stat, "ACW_SURV_Rank_07_SmallGame", "KILLS", "AMMO_ARROW_SMALL_GAME", 1.000000f, false },
		{ Category::Survivalist, 8, WriteKind::Stat, "ACW_SURV_Rank_08_HomingTomahawk", "MADE", "AMMO_TOMAHAWK_HOMING", 1.000000f, false },
		{ Category::Survivalist, 8, WriteKind::Stat, "ACW_SURV_Rank_08_ImprovedTomahawk", "MADE", "AMMO_TOMAHAWK_IMPROVED", 1.000000f, false },
		{ Category::Survivalist, 8, WriteKind::Stat, "ACW_SURV_Rank_08_VolatileDynamite", "MADE", "AMMO_DYNAMITE_VOLATILE", 1.000000f, false },
		{ Category::Survivalist, 8, WriteKind::Stat, "ACW_SURV_Rank_08_VolatileFireBottle", "MADE", "AMMO_MOLOTOV_VOLATILE", 1.000000f, false },
		{ Category::Survivalist, 9, WriteKind::Stat, "ACW_SURV_Rank_09_HeavyFishCaught", "BIGGEST_FISH_CAUGHT", "", 19.000000f, true },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_Bluegill", "CAUGHT", "AT_FBLUEGIL", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_Bluegill", "CAUGHT", "AT_FBLUEGILL_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_BullheadCatfish", "CAUGHT", "AT_FBULLHEADCATFISH", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_BullheadCatfish", "CAUGHT", "AT_FBULLHEAD_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_ChainPickerel", "CAUGHT", "AT_FCHAINPICKEREL", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_ChainPickerel", "CAUGHT", "AT_FPICKEREL_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_ChannelCatfish", "CAUGHT", "AT_FCHANNELCATFISH", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_LakeSturgeon", "CAUGHT", "AT_FLAKESTURGEON", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_LakeSturgeon", "CAUGHT", "AT_FSTURGEON_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_LargemouthBass", "CAUGHT", "AT_FLARGEMOUTHBASS", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_LargemouthBass", "CAUGHT", "AT_FLGBASS_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_LongnoseGar", "CAUGHT", "AT_FLONGNOSEGAR", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_LongnoseGar", "CAUGHT", "AT_FGAR_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_Muskie", "CAUGHT", "AT_FMUSKIE", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_Muskie", "CAUGHT", "AT_FMUSKIE_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_NorthernPike", "CAUGHT", "AT_FNORTHERNPIKE", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_NorthernPike", "CAUGHT", "AT_FPIKE_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_Perch", "CAUGHT", "AT_FPERCH", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_Perch", "CAUGHT", "AT_FPERCH_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_RedfinPickerel", "CAUGHT", "AT_FREDFINPICKEREL", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_RedfinPickerel", "CAUGHT", "AT_FREDFIN_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_RockBass", "CAUGHT", "AT_FROCKBASS", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_RockBass", "CAUGHT", "AT_FROCKBASS_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_SmallmouthBass", "CAUGHT", "AT_FSMALLMOUTHBASS", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_SmallmouthBass", "CAUGHT", "AT_FSMBASS_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_SockeyeSalmon", "CAUGHT", "AT_FSALMONSOCKEYE", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_SockeyeSalmon", "CAUGHT", "AT_FSALMON_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_SteelheadTrout", "CAUGHT", "AT_FRAINBOWTROUT", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_SteelheadTrout", "CAUGHT", "AT_FTROUT_LEGENDARY", 1.000000f, false },
		{ Category::WeaponsExpert, 1, WriteKind::Stat, "ACW_WEAP_Rank_01_KnifeKills", "KILLS", "KNIFE", 3.000000f, false },
		{ Category::WeaponsExpert, 1, WriteKind::Stat, "ACW_WEAP_Rank_01_KnifeKills", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 2, WriteKind::Stat, "ACW_WEAP_Rank_02_ThrowingKnife", "KILLS", "TH_KNIVES", 3.000000f, false },
		{ Category::WeaponsExpert, 3, WriteKind::Stat, "ACW_WEAP_Rank_03_Tomahawk", "KILLS", "BIRDS_OF_PREY", 3.000000f, false },
		{ Category::WeaponsExpert, 3, WriteKind::Stat, "ACW_WEAP_Rank_03_Tomahawk", "KILLS", "TH_TOMAHAWK", 1.000000f, false },
		{ Category::WeaponsExpert, 4, WriteKind::Stat, "ACW_WEAP_Rank_04_ShotgunCraftedAmmo", "KILLS", "AMMO_SHOTGUN_BUCKSHOT_INCENDIARY", 10.000000f, false },
		{ Category::WeaponsExpert, 4, WriteKind::Stat, "ACW_WEAP_Rank_04_ShotgunCraftedAmmo", "KILLS", "AMMO_SHOTGUN_SLUG_EXPLOSIVE", 10.000000f, false },
		{ Category::WeaponsExpert, 4, WriteKind::Stat, "ACW_WEAP_Rank_04_ShotgunCraftedAmmo", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 5, WriteKind::Stat, "ACW_WEAP_Rank_05_Mounted", "KILLS", "MOUNTED_PED", 5.000000f, false },
		{ Category::WeaponsExpert, 5, WriteKind::Stat, "ACW_WEAP_Rank_05_Mounted", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 5, WriteKind::Stat, "ACW_WEAP_Rank_05_Mounted", "KILLS", "TH_KNIVES", 1.000000f, false },
		{ Category::WeaponsExpert, 5, WriteKind::Stat, "ACW_WEAP_Rank_05_Mounted", "KILLS", "ONE_SHOT", 1.000000f, false },
		{ Category::WeaponsExpert, 6, WriteKind::Stat, "ACW_WEAP_Rank_06_Dynamite", "KILLS", "ENEMY", 4.000000f, false },
		{ Category::WeaponsExpert, 6, WriteKind::Stat, "ACW_WEAP_Rank_06_Dynamite", "KILLS", "TH_DYNAMITE", 1.000000f, false },
		{ Category::WeaponsExpert, 7, WriteKind::Stat, "ACW_WEAP_Rank_07_Tomahawk", "KILLS", "FROM_RECENT_PICKUP", 4.000000f, false },
		{ Category::WeaponsExpert, 7, WriteKind::Stat, "ACW_WEAP_Rank_07_Tomahawk", "KILLS", "TH_TOMAHAWK", 1.000000f, false },
		{ Category::WeaponsExpert, 7, WriteKind::Stat, "ACW_WEAP_Rank_07_Tomahawk", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 8, WriteKind::Stat, "ACW_WEAP_Rank_08_Sidearm", "KILLS", "CI_TAG_LONG_BARRELED_SIDEARM", 15.000000f, false },
		{ Category::WeaponsExpert, 9, WriteKind::Stat, "ACW_WEAP_Rank_09_Bow", "KILLS", "FROM_BEHIND", 9.000000f, false },
		{ Category::WeaponsExpert, 9, WriteKind::Stat, "ACW_WEAP_Rank_09_Bow", "KILLS", "UNAWARE", 1.000000f, false },
		{ Category::WeaponsExpert, 9, WriteKind::Stat, "ACW_WEAP_Rank_09_Bow", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 9, WriteKind::Stat, "ACW_WEAP_Rank_09_Bow", "KILLS", "SN_BOW", 1.000000f, false },
		{ Category::WeaponsExpert, 10, WriteKind::Stat, "ACW_WEAP_Rank_10_Bear", "KILLED", "AT_BEAR_GRIZZLY", 1.000000f, false },
		{ Category::WeaponsExpert, 10, WriteKind::Stat, "ACW_WEAP_Rank_10_Bear", "KILLS", "NO_DAMAGE_RECEIVED", 1.000000f, false },
		{ Category::WeaponsExpert, 10, WriteKind::Stat, "ACW_WEAP_Rank_10_Bear", "KILLS", "TH_KNIVES", 1.000000f, false },
		{ Category::WeaponsExpert, 10, WriteKind::Stat, "ACW_WEAP_Rank_10_Bear", "KILLS", "ONE_WEAPON", 1.000000f, false },
	};

	// Horseman rank 10's 9 goals each only ever check whether a specific
	// breed's compendium entry has been marked "broken" -- there's no
	// persisted counter or stat behind it at all (see kKnownWrites' own
	// comment above the rank-10 rows). The real script (player_horse.ysc.c,
	// ~line 6546) does this by calling
	// COMPENDIUM::COMPENDIUM_HORSE_WILD_BROKEN(pedIndex) on the wild horse
	// ped that was just tamed -- the native reads THAT ped's own model to
	// figure out which breed's entry to credit, it isn't told the breed
	// directly. So this spawns a short-lived, no-longer-needed ped of the
	// requested breed's model a few meters from the player, calls the
	// native on it once, then deletes it immediately -- the player never
	// sees it appear.
	bool SpawnAndBreakCompendiumHorse(Hash modelHash, const char* label)
	{
		if (!STREAMING::IS_MODEL_IN_CDIMAGE(modelHash) || !STREAMING::IS_MODEL_VALID(modelHash))
		{
			Log::Write("SpawnAndBreakCompendiumHorse: model {:#x} for goal '{}' is not a valid/streamable "
				"model in this build.", modelHash, label);
			return false;
		}

		STREAMING::REQUEST_MODEL(modelHash, false);
		for (int attempt = 0; attempt < 100 && !STREAMING::HAS_MODEL_LOADED(modelHash); attempt++)
			WAIT(50);

		if (!STREAMING::HAS_MODEL_LOADED(modelHash))
		{
			Log::Write("SpawnAndBreakCompendiumHorse: model {:#x} for goal '{}' never finished loading "
				"after 5s.", modelHash, label);
			STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(modelHash);
			return false;
		}

		Ped playerPed = PLAYER::PLAYER_PED_ID();
		Vector3 coords = ENTITY::GET_ENTITY_COORDS(playerPed, true, true);
		// A few meters off to the side is enough to avoid spawning inside
		// the player; exact placement doesn't matter since this ped is
		// deleted again within the same call, before a render frame.
		Ped horse = PED::CREATE_PED(modelHash, coords.x + 3.0f, coords.y + 3.0f, coords.z, 0.0f, false, true, false, false);
		STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(modelHash);

		if (!ENTITY::DOES_ENTITY_EXIST(horse))
		{
			Log::Write("SpawnAndBreakCompendiumHorse: CREATE_PED failed for goal '{}' (model {:#x}).",
				label, modelHash);
			return false;
		}

		COMPENDIUM::COMPENDIUM_HORSE_WILD_BROKEN(horse);
		Log::Write("SpawnAndBreakCompendiumHorse: called COMPENDIUM_HORSE_WILD_BROKEN on a spawned ped "
			"for goal '{}' (model {:#x}).", label, modelHash);

		ENTITY::SET_ENTITY_AS_MISSION_ENTITY(horse, true, true);
		PED::DELETE_PED(&horse);
		return true;
	}

	std::string g_lastFailureReason;
}

namespace ChallengeCheat
{
	const char* GetDisplayName(Category category)
	{
		return Info(category).displayName;
	}

	const std::string& GetLastAdvanceFailureReason()
	{
		return g_lastFailureReason;
	}

	int GetRanksCompleted(Category category)
	{
		return STATS::CHAL_GET_NUM_RANKS_COMPLETED(RootHash(category));
	}

	int GetMaxRanks(Category category)
	{
		return STATS::CHAL_GET_MAX_RANKS(RootHash(category));
	}

	bool AdvanceRank(Category category)
	{
		g_lastFailureReason.clear();

		// Scoped to this function's whole lifetime (not just the write-
		// application loop below) so its destructor clears any still-armed
		// timed-ride goal target and disables the hook on EVERY return path.
		// If the targeted RDX is observed first, the detour calls the
		// unlock/fallback function and disables itself immediately.
		std::optional<TimedRideHook::ScopedTimedRideUnlock> timedRideUnlock;

		Hash chalHash = RootHash(category);
		int before = STATS::CHAL_GET_NUM_RANKS_COMPLETED(chalHash);
		int maxRanks = STATS::CHAL_GET_MAX_RANKS(chalHash);

		if (before >= maxRanks)
		{
			Log::Write("AdvanceRank({}): already at max rank ({}/{})",
				Info(category).displayName, before, maxRanks);
			return false;
		}

		int targetRank = before + 1;

		// Pre-check live requirements BEFORE writing anything for this rank
		// -- live-CONFIRMED (2026-09-17, Horseman rank 1) that a goal's
		// AIConditional wrapper can be a real runtime gate: writing
		// KILLED/AT_RABBIT to 5 did nothing until the player was actually
		// on horseback when the write happened. Checking Requirement::OnMount
		// up front avoids burning a write (and the ~3s poll below) on an
		// attempt that's guaranteed to fail, and tells the player exactly
		// what to do instead of a bare "didn't work."
		for (const auto& w : kKnownWrites)
		{
			if (w.category != category || w.rank != targetRank)
				continue;

			if (w.requirement == Requirement::OnMount && !PED::IS_PED_ON_MOUNT(PLAYER::PLAYER_PED_ID()))
			{
				g_lastFailureReason = "You must be on horseback for this one -- mount up and try again.";
				Log::Write("AdvanceRank({}): rank {}'s goal '{}' requires being on horseback -- "
					"mount up and try again. No change made.",
					Info(category).displayName, targetRank, w.label);
				return false;
			}
			if (w.requirement == Requirement::OnMovingTrain)
			{
				Log::Write("AdvanceRank({}): NOTE -- rank {}'s goal '{}' normally requires being on a "
					"moving train (no native check found for this yet, attempting the write anyway).",
					Info(category).displayName, targetRank, w.label);
			}
			if (w.requirement == Requirement::DeadeyeActive)
			{
				Log::Write("AdvanceRank({}): NOTE -- rank {}'s goal '{}' normally requires Dead Eye "
					"being active (no native check found for this yet, attempting the write anyway).",
					Info(category).displayName, targetRank, w.label);
			}
		}

		int appliedCount = 0;
		for (const auto& w : kKnownWrites)
		{
			if (w.category != category || w.rank != targetRank)
				continue;

			if (w.kind == WriteKind::Stat)
			{
				StatId id{
					static_cast<Hash>(rage::Joaat(w.baseId)),
					static_cast<Hash>(rage::Joaat(w.permId))
				};
				// Real script call sites (e.g. dominoes_sp.ysc.c's func_606)
				// only ever use _STAT_ID_INCREMENT_INT/_FLOAT for progress --
				// never STAT_ID_SET_INT/_FLOAT, which a live test showed does
				// NOT move the challenge rank counter even with a correct,
				// real stat name. Increment instead (matches what real
				// gameplay actually calls), and read back immediately after
				// to separate "the stat write itself didn't land" from "it
				// landed but the challenge system didn't react to it."
				if (w.isFloat)
				{
					STATS::_STAT_ID_INCREMENT_FLOAT(reinterpret_cast<Any*>(&id), w.value);
					float readback = 0.0f;
					BOOL ok = STATS::STAT_ID_GET_FLOAT(reinterpret_cast<Any*>(&id), &readback);
					Log::Write("AdvanceRank({}): incremented stat BaseId='{}' PermutationId='{}' (goal '{}', rank {}) by {:.2f} -- readback: {} ({:.2f})",
						Info(category).displayName, w.baseId, w.permId, w.label, targetRank, w.value, ok ? "ok" : "FAILED", readback);
				}
				else
				{
					int value = static_cast<int>(w.value + 0.5f);
					STATS::_STAT_ID_INCREMENT_INT(reinterpret_cast<Any*>(&id), value);
					int readback = 0;
					BOOL ok = STATS::STAT_ID_GET_INT(reinterpret_cast<Any*>(&id), &readback);
					Log::Write("AdvanceRank({}): incremented stat BaseId='{}' PermutationId='{}' (goal '{}', rank {}) by {} -- readback: {} ({})",
						Info(category).displayName, w.baseId, w.permId, w.label, targetRank, value, ok ? "ok" : "FAILED", readback);
				}
			}
			else if (w.kind == WriteKind::ScriptGoal)
			{
				Hash goalHash = static_cast<Hash>(rage::Joaat(w.label));
				int value = static_cast<int>(w.value + 0.5f);
				// CHAL_SET_GOAL_PROGRESS_INT live-tested and failed here
				// (Gambler rank 6, real ACW_GAMB_Rank_06_Blackjack_RHO/VAN
				// goal names) even though these ARE genuinely script-
				// sourced -- same SET-vs-ADD/INCREMENT split already found
				// for STAT_ID_SET_INT vs _STAT_ID_INCREMENT_INT. Using ADD
				// instead on the same theory.
				STATS::CHAL_ADD_GOAL_PROGRESS_INT(chalHash, goalHash, value);
				Log::Write("AdvanceRank({}): added {} progress to script goal '{}' (rank {})",
					Info(category).displayName, value, w.label, targetRank);
			}
			else if (w.kind == WriteKind::PointToPointHook)
			{
				std::uint64_t timedRideGoalIndex = static_cast<std::uint64_t>(w.value + 0.5f);
				if (!timedRideUnlock)
					timedRideUnlock.emplace(timedRideGoalIndex);

				if (!timedRideUnlock->IsReady())
				{
					Log::Write("AdvanceRank({}): FAILED to install native timed-ride completion hook for "
						"goal '{}' (rank {}) -- signature not found or MinHook error (see log above). "
						"Not counted as an applied write.",
						Info(category).displayName, w.label, targetRank);
					timedRideUnlock.reset();
					continue;
				}

				Log::Write("AdvanceRank({}): enabled timed-ride unlock hook for goal '{}' (rank {}, "
					"timed-ride goal index/RDX={:#x}) -- hook will disable after the first matching call "
					"or when this AdvanceRank() call returns.",
					Info(category).displayName, w.label, targetRank, timedRideGoalIndex);
			}
			else // WriteKind::HorseCompendium
			{
				if (!SpawnAndBreakCompendiumHorse(w.modelHash, w.label))
				{
					Log::Write("AdvanceRank({}): FAILED to spawn/break compendium horse for goal '{}' "
						"(rank {}, model {:#x}) -- model never loaded or CREATE_PED failed (see log "
						"above). Not counted as an applied write.",
						Info(category).displayName, w.label, targetRank, w.modelHash);
					continue;
				}
			}
			appliedCount++;
		}

		if (appliedCount == 0)
		{
			Log::Write("AdvanceRank({}): no known write for rank {} yet -- unsupported goal type "
				"(compendium/collectable-list/group-stat/timed-ride, see CLAUDE.md). No change made.",
				Info(category).displayName, targetRank);
			return false;
		}

		// Live-confirmed 2026-09-17: CHAL_GET_NUM_RANKS_COMPLETED does NOT
		// reflect a stat write in the same tick it happened on -- a real
		// test showed the rank counter still read the old value
		// immediately after a correct, readback-confirmed stat write, but
		// the in-game toast/menu DID show the rank completing a moment
		// later once the player waited. So this polls for up to ~3 seconds
		// (WAIT() yields back to the game between checks, giving whatever
		// background re-evaluation the challenge system does a chance to
		// run) before concluding the write didn't take -- never claims
		// success without an actual observed increase, just gives the game
		// a realistic window to report one.
		for (int attempt = 0; attempt < 6; attempt++)
		{
			int after = STATS::CHAL_GET_NUM_RANKS_COMPLETED(chalHash);
			if (after > before)
			{
				Log::Write("AdvanceRank({}): CONFIRMED -- rank {} -> {} ({} write(s) applied, "
					"observed after {} poll(s))", Info(category).displayName, before, after, appliedCount, attempt);
				return true;
			}
			WAIT(500);
		}

		int finalCount = STATS::CHAL_GET_NUM_RANKS_COMPLETED(chalHash);
		Log::Write("AdvanceRank({}): applied {} write(s) for rank {} but the rank counter did NOT "
			"increase after ~3s of polling (still {}).",
			Info(category).displayName, appliedCount, targetRank, finalCount);
		return false;
	}

	int CompleteChallenge(Category category)
	{
		int advanced = 0;
		while (AdvanceRank(category))
			advanced++;

		Log::Write("CompleteChallenge({}): advanced {} rank(s) this call, now {}/{}",
			Info(category).displayName, advanced, GetRanksCompleted(category), GetMaxRanks(category));
		return advanced;
	}
}
