/*
	ChallengeCheat -- research trail and current coverage.

	GOAL: advance/complete RDR2's 9 singleplayer "Challenges" (Bandit,
	Explorer, Gambler, Herbalist, Horseman, Master Hunter, Sharpshooter,
	Survivalist, Weapons Expert) through the game's own real progress
	system, so that whatever reward-grant logic normally reacts to a
	completed rank still fires.

	NATIVE SURFACE (external\ScriptHookSDK\inc\natives.h):
	  STATS::CHAL_GET_NUM_RANKS_COMPLETED(Hash chalHash) -> int
	  STATS::CHAL_GET_MAX_RANKS(Hash chalHash) -> int
	  STATS::CHAL_ADD_GOAL_PROGRESS_INT(Hash chalHash, Hash goalHash, int value)
	  STATS::_STAT_ID_INCREMENT_INT / _STAT_ID_INCREMENT_FLOAT(StatId* statId, value)
	  COLLECTABLE::_COLLECTABLE_INCREMENT_NUM_FOUND, COMPENDIUM::COMPENDIUM_HORSE_WILD_BROKEN
	  (the SET variants -- CHAL_SET_GOAL_PROGRESS_INT, STAT_ID_SET_INT/FLOAT
	  -- were tried first and live-tested NOT to move the rank counter; see
	  ApplyRankProgress()'s comments)
	  StatId is a documented struct right above STAT_ID_IS_VALID in
	  natives.h: { alignas(8) Hash BaseId; alignas(8) Hash PermutationId; }

	ROOT HASHES: confirmed directly from
	D:\Backup\Stuff\RDR2 Shit\Scripts\1491.50\script_rel\pause_menu.ysc.c's
	own index -> hash switch (~line 7147) -- see kCategoryInfo below.

	THE REAL GOAL REGISTRY -- and a live-fire lesson learned the hard way
	(2026-09-17): the user first extracted `challenges_sp.meta`/
	`goals_sp.meta` from disk and handed them over, and an earlier version
	of this file was built entirely against them, using
	CHAL_SET_GOAL_PROGRESS_INT(chalHash, joaat(goalName), desiredGoal) --
	the goal's own name, taken as a literal goalHash -- as a UNIVERSAL
	mechanism for every goal regardless of how it's normally tracked. That
	shipped, built clean, and failed live: 3 for 3 AdvanceRank attempts
	(Bandit rank 2, Explorer rank 5, Gambler rank 6) applied without error
	but never moved CHAL_GET_NUM_RANKS_COMPLETED. Digging into WHY
	revealed the real problem: those two files were not vanilla data at
	all -- their header comment admitted as much ("Gambler #2-10 auto
	complete") -- someone had already rewritten several goals' `scoreParam`
	to point at unrelated, trivially-satisfiable stats (e.g. Gambler rank
	6's "win blackjack at Rhodes" goal had been rewired to just check
	TOTAL_PLAYING_GAME_TIME >= 10). The user correctly called this
	"BS from a mod" and had the real files pulled directly from the game's
	own RPFs instead (`RDR2-RPF-Tool`, headless CLI mode added to it this
	session specifically for this -- see that tool's own HeadlessQuery.cs/
	RPF8.cs for the read-only load path added so it can run while RDR2.exe
	has the RPF open). The real files live in `update_1.rpf` at
	`common/data/stats_and_challenges/{goals,challenges}_sp.meta` -- NOT
	in the base `data_0.rpf`, and NOT in the later update_2/3/4.rpf either
	(this specific path apparently hasn't needed re-patching since
	update_1). Both real files are archived at
	`D:\Backup\Stuff\RDR2 Shit\{goals,challenges}_sp.meta` (the fake ones
	are kept alongside as `*_FAKE_MOD.meta` for reference/comparison, not
	used by anything).

	Against the REAL data, the picture is meaningfully different: only 10
	of 138 goals are genuinely `StatsGoalScoreSourceScript`-sourced (up
	from the fake file's 2, but still a small minority) -- these are the
	only goals `CHAL_SET_GOAL_PROGRESS_INT`-by-name is actually the
	correct, real mechanism for (it's literally what the vanilla game
	itself would call for them). The other 102 non-unsupported goals are
	genuinely `StatsGoalScoreSourceStat`-sourced, each naming a real,
	sane-looking stat (`KILLED`/`AT_RABBIT`, `LONGEST_DIST_DRAGGED`,
	`HOLD_UPS_IN_TOWN`, etc. -- these line up exactly with the plain-
	English challenge descriptions the user separately supplied, e.g.
	Horseman rank 4's `LONGEST_DIST_DRAGGED=1006` for "drag a victim
	3,300 feet"). Since the live test already showed writing the GOAL's
	own progress counter does NOT retroactively satisfy a stat-sourced
	goal's real completion check, this version writes the REAL underlying
	stat(s) directly instead -- via `_STAT_ID_INCREMENT_INT`/`_FLOAT`, the
	calls real gameplay scripts make for progress (e.g. dominoes_sp's
	func_606). STAT_ID_SET_INT/FLOAT was tried first and live-tested not
	to move the rank counter even with the correct stat.

	`kKnownWrites` below (302 rows, including hand-added HorseCompendium,
	Collectable and StatDistinct rows -- see those sections' own comments) was
	generated by parsing both real
	meta files with Python (`xml.etree.ElementTree`): `challenges_sp.meta`
	gives every rank's real goal name(s) in order; `goals_sp.meta`'s
	`<scoreParam>` tree is walked recursively per goal, descending through
	wrapper types (`AIConditional`/`Binding`/`Resetable`/`IntSum`/
	`IntGroupSum`) to find every leaf `StatsGoalScoreSourceStat` (emitting
	one write row per leaf, at the nearest enclosing `desiredGoal` -- a sum
	goal's every contributing stat gets pushed to the FULL combined target,
	a safe overshoot for a "sum >= N" check) or the single
	`StatsGoalScoreSourceScript` `<id>` (emitting one ScriptGoal row).…
	Goals whose only source is a compendium entry, a "collect N of this
	item list" group, a "reach threshold on N different stats in a named
	group" group, or (3 Horseman ranks) no `<scoreParam>` at all (a
	location-to-location timed ride, evaluated live, not from a persisted
	number) are NOT in the auto-generated part of the table -- see the
	coverage table in CLAUDE.md. Two of those buckets got hand-added rows
	after the fact: `WriteKind::HorseCompendium` (Horseman rank 10) and
	`WriteKind::Collectable` (Explorer ranks 2-10, see below).

	CURRENT COVERAGE: every rank of Bandit, Explorer, Gambler, Horseman,
	Survivalist, and Weapons Expert (all 1-10). Sharpshooter/Master
	Hunter/Herbalist each hit a real ceiling at a specific rank whose
	ONLY goal has no known mechanism at all yet -- see CLAUDE.md's table.
	`AdvanceRank()`/`CompleteChallenge()` are fire-and-forget (2026-09-19):
	they report success once the write(s) were applied, without polling
	`CHAL_GET_NUM_RANKS_COMPLETED` -- the engine often takes longer than any
	reasonable poll window to re-evaluate, so polling produced false
	failures. See ChallengeCheat.h's own comments on both functions.

	HORSEMAN RANKS 3/6/9 (the 3 StatsGoalPointToPoint "timed ride" goals,
	no <scoreParam>, no script or documented native anywhere near them --
	see this file's own coverage notes and CLAUDE.md): CONFIRMED LIVE
	2026-09-17 that the completion check itself is `sub_140BAC640` in the
	analyzed build (RDR2.exe+0xBAC640), found by planting a distinctive
	marker value (durationSeconds 300 -> 13371337) via an LML-overridden
	goals_sp.meta and using Cheat Engine's "find out what accesses this
	address" on it.

	A first fix patched one internal conditional jump to force the
	function's own null-tracking-context fallback path unconditionally --
	live-confirmed to complete Horseman rank 3, but with a bug: advancing
	rank 3 also silently completed ranks 6 and 9 later, with no hook ever
	installed for them specifically. A logging-only MinHook detour (zero
	effect on behavior, just observed arguments) explained why:
	sub_140BAC640 is called once per PointToPoint goal INSTANCE during a
	single shared periodic re-evaluation pass -- three calls observed
	back-to-back in the very same tick, one per goal, each with a
	different `a1` and, critically, a different RDX value (0x161/0x164/
	0x167 for ranks 3/6/9 respectively, consistently spaced by 3 -- a
	per-goal index). The old unconditional patch had no way to tell these
	apart, so it forced success for whichever goal(s) happened to be
	evaluated during its brief patch window -- not always just the one
	requested.

	`WriteKind::PointToPointHook` below now uses a real MinHook detour
	(TimedRideHook.h/.cpp) that inspects RDX and only forces the fallback
	path (`return (char)sub_140B9842C(a1)`, exactly replicating the
	original function's own behavior for an untracked goal) when RDX
	matches the SPECIFIC goal being targeted -- every other call (any
	other RDX) passes straight through to the real evaluation, completely
	unaffected. The hook is enabled for the targeted AdvanceRank() attempt
	and disables itself immediately after the first matching RDX calls the
	unlock/fallback function, so it does not remain hooked for the rest of
	the poll window once the intended goal has fired.
*/

#include "ChallengeCheat.h"
#include "Log.h"
#include "Localization.h"
#include "script.h"
#include "TimedRideHook.h"

#include "..\external\RDR-Classes\rage\joaat.hpp"

#include <cstddef>
#include <cstdint>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <string>
#include <vector>
#include <optional>
#include <array>

namespace
{
	using ChallengeCheat::Category;

	// Documented in natives.h directly above STAT_ID_IS_VALID:
	//   struct StatId { alignas(8) Hash BaseId; alignas(8) Hash PermutationId; }
	struct StatId
	{
		alignas(8) Hash BaseId;
		alignas(8) Hash PermutationId;
	};

	struct CategoryInfo
	{
		std::string_view displayName;
		std::string_view rootHashName;
	};

	// Order matches Category's enum order, which matches pause_menu.ysc.c's
	// own index switch exactly (see this file's header comment).
	constexpr CategoryInfo kCategoryInfo[] = {
		{ "Bandit",         "sp_chal_band_root" },
		{ "Explorer",       "sp_chal_expl_root" },
		{ "Gambler",        "sp_chal_gamb_root" },
		{ "Herbalist",      "sp_chal_herb_root" },
		{ "Horseman",       "sp_chal_horse_root" },
		{ "Master Hunter",  "sp_chal_hunt_root" },
		{ "Sharpshooter",   "sp_chal_shot_root" },
		{ "Survivalist",    "sp_chal_surv_root" },
		{ "Weapons Expert", "sp_chal_weap_root" },
	};

	const CategoryInfo& Info(Category category)
	{
		return kCategoryInfo[static_cast<std::size_t>(category)];
	}

	Hash RootHash(Category category)
	{
		return static_cast<Hash>(rage::Joaat(Info(category).rootHashName));
	}

	enum class WriteKind
	{
		Stat,            // write baseId/permId's real named stat directly
		StatAtOnce,      // like Stat, but the goal has no usable partial step (a record like biggest fish/highest bounty/furthest kill/longest drag, a dollar amount, or a progress window that expires and resets) -- Step applies the full value, same as Complete; a +1 step would take thousands of clicks
		StatSum,         // like Stat, but the goal SUMS several stats toward one target (IntSum, completeAll=false) -- Step credits only the goal's first row per click; Complete writes every row's full value
		StatDistinct,    // like Stat, but the goal counts DISTINCT stats reaching 1 (group-sum of a capped template) -- Step credits ONE not-yet-picked row per click; Complete writes them all
		ScriptGoal,      // write the goal's own name via CHAL_ADD_GOAL_PROGRESS_INT
		PointToPointHook, // scoped binary patch of the native completion check -- see TimedRideHook.h
		HorseCompendium, // spawn modelHash's breed ped, call COMPENDIUM_HORSE_WILD_BROKEN, delete it
		Collectable,     // mark baseId's named collectable item found via COLLECTABLE::_COLLECTABLE_INCREMENT_NUM_FOUND
	};

	// A handful of real goals wrap their scoreParam in a
	// StatsGoalParamAIConditional -- live-CONFIRMED (2026-09-17, Horseman
	// rank 1) that this is a real runtime gate checked at evaluation time,
	// not just a description of how the stat normally accumulates during
	// real play: writing the stat directly did nothing until the player
	// was actually on horseback when the write happened. Found by scanning
	// every goal in goals_sp.meta for an AIConditional wrapper's
	// <condition type="...">, not just the one that failed live.
	enum class Requirement
	{
		None,
		OnMount,       // CAIConditionIsOnMount -- checked live via PED::IS_PED_ON_MOUNT
		OnMovingTrain, // CAIConditionGoalContext (CHAL_CTX_ON_MOVING_TRAIN) -- checked via PLAYER::IS_PLAYER_RIDING_TRAIN
		ScopedKit,     // CAIConditionGoalContext (CHAL_CTX_SCOPED_KIT) -- checked via SCRIPT::_IS_GOAL_CONTEXT_ACTIVE
		DeadeyeActive, // CAIConditionPlayerIsDeadeyeActive -- checked via PLAYER::_IS_SPECIAL_ABILITY_ACTIVE + aiming
	};

	// Step: advance the CURRENT rank's goal(s) by one small increment (e.g.
	// "killed 1 more rabbit" toward a goal that needs 4) -- may or may not
	// complete the rank on its own. Complete: push the goal's full target in
	// one shot (the original design's only mode) -- always finishes the
	// current rank if the write lands. For WriteKind::PointToPointHook and
	// HorseCompendium there's no meaningful sub-unit to step through (each
	// row IS one atomic, all-or-nothing native call -- a timed-ride unlock or
	// one breed's compendium entry), so both modes apply every matching row
	// for those kinds identically.
	enum class WriteMode
	{
		Step,
		Complete,
	};

	struct KnownWrite
	{
		Category category;
		int rank; // 1-indexed: this write contributes to reaching this rank
		WriteKind kind;
		std::string_view label;  // goal name -- always the goal's real <name>, for logging
		std::string_view baseId; // Stat: statId BaseId ("" if this stat has none). Collectable: the collectable item's real name.
		std::string_view permId; // Stat only: statId PermutationId ("" if none)
		float value;
		bool isFloat; // Stat: increment as float vs int. ScriptGoal: always false (int goals only so far)
		Requirement requirement = Requirement::None;
		Hash modelHash = 0; // HorseCompendium only: the breed's ped model hash
	};

	// Centralizes the shared bookkeeping and logging for both stat types.
	// `amount` is the actual increment to apply -- a small fixed step for
	// WriteMode::Step, or write.value (the goal's full target, a safe
	// overshoot) for WriteMode::Complete. See ApplyRankProgress.
	void IncrementStatAndLog(
		const KnownWrite& write,
		StatId& id,
		const CategoryInfo& categoryInfo,
		int targetRank,
		std::string_view verb,
		float amount)
	{
		if (write.isFloat)
		{
			STATS::_STAT_ID_INCREMENT_FLOAT(reinterpret_cast<Any*>(&id), amount);
			float readback = 0.0f;
			BOOL ok = STATS::STAT_ID_GET_FLOAT(reinterpret_cast<Any*>(&id), &readback);
			Log::Write("{}({}): incremented stat BaseId='{}' PermutationId='{}' (goal '{}', rank {}) by {:.2f} -- readback: {} ({:.2f})",
				verb, categoryInfo.displayName, write.baseId, write.permId, write.label, targetRank, amount, ok ? "ok" : "FAILED", readback);
			return;
		}

		int value = static_cast<int>(amount + 0.5f);
		STATS::_STAT_ID_INCREMENT_INT(reinterpret_cast<Any*>(&id), value);
		int readback = 0;
		BOOL ok = STATS::STAT_ID_GET_INT(reinterpret_cast<Any*>(&id), &readback);
		Log::Write("{}({}): incremented stat BaseId='{}' PermutationId='{}' (goal '{}', rank {}) by {} -- readback: {} ({})",
			verb, categoryInfo.displayName, write.baseId, write.permId, write.label, targetRank, value, ok ? "ok" : "FAILED", readback);
	}

	// WriteKind::StatDistinct Step bookkeeping: how many of a goal's rows
	// Advance has credited so far this session, keyed by goal name. Not
	// persisted -- after a restart mid-rank, Complete finishes the rank.
	std::unordered_map<std::uint32_t, int> g_distinctStepsCredited; // key: rage::Joaat(goal name)

	// Auto-generated from the REAL challenges_sp.meta + goals_sp.meta
	// (extracted from update_1.rpf, NOT the fake mod copy -- see this
	// file's header comment). 302 write rows: the auto-generated Stat/
	// ScriptGoal/PointToPointHook rows plus hand-added HorseCompendium
	// (Horseman rank 10), Collectable (Explorer ranks 2-10) and StatDistinct
	// group rows -- see each section's own comment below.
	constexpr KnownWrite kKnownWrites[] = {
		{ Category::Bandit, 1, WriteKind::Stat, "ACW_BAND_Rank_01_Townsfolk", "HOLD_UPS_IN_TOWN", "", 5.000000f, false },
		{ Category::Bandit, 2, WriteKind::StatSum, "ACW_BAND_Rank_02_CoachRobberies", "", "AMBIENT_COACH_ROBBED", 2.000000f, false },
		{ Category::Bandit, 2, WriteKind::StatSum, "ACW_BAND_Rank_02_CoachRobberies", "STOLEN_WAGONS_SOLD", "", 2.000000f, false },
		{ Category::Bandit, 3, WriteKind::Stat, "ACW_BAND_Rank_03_ShopRobberies", "CASH_REGISTERS_ROBBED", "", 4.000000f, false },
		{ Category::Bandit, 4, WriteKind::StatSum, "ACW_BAND_Rank_04_CoachesRobbedInADay", "", "AMBIENT_COACH_ROBBED", 3.000000f, false },
		{ Category::Bandit, 4, WriteKind::StatSum, "ACW_BAND_Rank_04_CoachesRobbedInADay", "STOLEN_WAGONS_SOLD", "", 3.000000f, false },
		{ Category::Bandit, 5, WriteKind::StatAtOnce, "ACW_BAND_Rank_05_HighestBounty", "HIGHEST_BOUNTY", "", 25000.000000f, false },
		{ Category::Bandit, 6, WriteKind::Stat, "ACW_BAND_Rank_06_HorsesFenced", "STOLEN_HORSES_SOLD", "", 5.000000f, false },
		{ Category::Bandit, 7, WriteKind::StatAtOnce, "ACW_BAND_Rank_07_StealCash", "HOLD_UP_CASH", "CIVILIAN", 5000.000000f, false },
		{ Category::Bandit, 8, WriteKind::Stat, "ACW_BAND_Rank_08_WagonsFenced", "STOLEN_WAGONS_SOLD", "", 7.000000f, false },
		{ Category::Bandit, 9, WriteKind::Stat, "ACW_BAND_Rank_09_HogtiedTrainTracks", "TIMES_HOGTIED_ONTO_TRAIN_TRACKS", "", 3.000000f, false },
		{ Category::Bandit, 10, WriteKind::Stat, "ACW_BAND_Rank_10_TrainRobberies", "ROB_COMPLETED", "TRAIN", 5.000000f, false },
		{ Category::Explorer, 1, WriteKind::ScriptGoal, "ACW_EXPL_Rank_01_Treasure", "", "", 1.000000f, false },
		// Explorer ranks 2-10 (ACW_EXPL_Rank_{02..10}_Treasure) are all
		// StatsGoalParamIntGroupSum over the SAME 18-item
		// StatsGoalScoreSourceGroupCollectableList pool (TREASURE_HUNT_LOOT_
		// {02,03,04,06,07,08,10,11,12,14,15,17,18,19,21,22,23,24} -- 01/05/09/
		// 13/16/20 are excluded, per the real goals_sp.meta's own comment,
		// because they're the treasure-map pickups that start each hunt
		// chain, not loot), with desiredGoal climbing 1..9 -- found by
		// reading the real goals_sp.meta directly (kKnownWrites' generator
		// never emitted a row for these; it only handled Stat/Script leaves,
		// not GroupCollectableList). The real mechanism: treasure_hunter.ysc.c
		// (~line 218) calls COLLECTABLE::_COLLECTABLE_INCREMENT_NUM_FOUND(
		// itemHash, 1) once per real loot pickup, the same native the item's
		// own pickup state machine uses -- calling it directly has no other
		// side effect (the script's separate "big reward" toast switch for a
		// few item IDs lives in the pickup state machine itself, not behind
		// this native). Each rank below targets a distinct, not-yet-used pool
		// item and pushes the FULL rank target as the increment amount (same
		// "safe overshoot" convention as this table's auto-generated Stat sum
		// rows) so each row alone satisfies that rank's desiredGoal regardless
		// of what earlier ranks already contributed to the shared group sum.
		// Builds clean; not yet live-tested.
		{ Category::Explorer, 2, WriteKind::Collectable, "ACW_EXPL_Rank_02_Treasure", "TREASURE_HUNT_LOOT_02", "", 1.000000f, false },
		{ Category::Explorer, 3, WriteKind::Collectable, "ACW_EXPL_Rank_03_Treasure", "TREASURE_HUNT_LOOT_03", "", 2.000000f, false },
		{ Category::Explorer, 4, WriteKind::Collectable, "ACW_EXPL_Rank_04_Treasure", "TREASURE_HUNT_LOOT_04", "", 3.000000f, false },
		{ Category::Explorer, 5, WriteKind::Collectable, "ACW_EXPL_Rank_05_Treasure", "TREASURE_HUNT_LOOT_06", "", 4.000000f, false },
		{ Category::Explorer, 6, WriteKind::Collectable, "ACW_EXPL_Rank_06_Treasure", "TREASURE_HUNT_LOOT_07", "", 5.000000f, false },
		{ Category::Explorer, 7, WriteKind::Collectable, "ACW_EXPL_Rank_07_Treasure", "TREASURE_HUNT_LOOT_08", "", 6.000000f, false },
		{ Category::Explorer, 8, WriteKind::Collectable, "ACW_EXPL_Rank_08_Treasure", "TREASURE_HUNT_LOOT_10", "", 7.000000f, false },
		{ Category::Explorer, 9, WriteKind::Collectable, "ACW_EXPL_Rank_09_Treasure", "TREASURE_HUNT_LOOT_11", "", 8.000000f, false },
		{ Category::Explorer, 10, WriteKind::Collectable, "ACW_EXPL_Rank_10_Treasure", "TREASURE_HUNT_LOOT_12", "", 9.000000f, false },
		{ Category::Gambler, 1, WriteKind::Stat, "ACW_GAMB_Rank_01_Poker", "WINS", "POKER_HAND", 5.000000f, false },
		{ Category::Gambler, 2, WriteKind::Stat, "ACW_GAMB_Rank_02_Blackjack", "WINS", "BLACKJACK_DOUBLED_DOWN", 5.000000f, false },
		{ Category::Gambler, 3, WriteKind::Stat, "ACW_GAMB_Rank_03_FiveFingerFillet", "WINS", "FIVE_FINGER", 3.000000f, false },
		{ Category::Gambler, 4, WriteKind::ScriptGoal, "ACW_GAMB_Rank_04_Poker_FNS", "", "", 1.000000f, false },
		{ Category::Gambler, 4, WriteKind::ScriptGoal, "ACW_GAMB_Rank_04_Poker_SDN", "", "", 1.000000f, false },
		{ Category::Gambler, 4, WriteKind::ScriptGoal, "ACW_GAMB_Rank_04_Poker_VAL", "", "", 1.000000f, false },
		{ Category::Gambler, 5, WriteKind::Stat, "ACW_GAMB_Rank_05_Dominoes", "WINS", "DOMINOES_NO_DRAWS", 3.000000f, false },
		{ Category::Gambler, 6, WriteKind::ScriptGoal, "ACW_GAMB_Rank_06_Blackjack_RHO", "", "", 1.000000f, false },
		{ Category::Gambler, 6, WriteKind::ScriptGoal, "ACW_GAMB_Rank_06_Blackjack_VAN", "", "", 1.000000f, false },
		{ Category::Gambler, 7, WriteKind::ScriptGoal, "ACW_GAMB_Rank_07_FiveFinger_STR", "", "", 1.000000f, false },
		{ Category::Gambler, 7, WriteKind::ScriptGoal, "ACW_GAMB_Rank_07_FiveFinger_VAL", "", "", 1.000000f, false },
		{ Category::Gambler, 7, WriteKind::ScriptGoal, "ACW_GAMB_Rank_07_FiveFinger_VAN", "", "", 1.000000f, false },
		{ Category::Gambler, 8, WriteKind::Stat, "ACW_GAMB_Rank_08_Blackjack", "WINS", "BLACKJACK_4_HITS", 3.000000f, false },
		{ Category::Gambler, 9, WriteKind::StatAtOnce, "ACW_GAMB_Rank_09_Dominoes", "WIN_STREAK", "DOMINOES_GAME", 3.000000f, false },
		{ Category::Gambler, 10, WriteKind::StatAtOnce, "ACW_GAMB_Rank_10_PokerHands", "WIN_STREAK", "POKER_HAND", 3.000000f, false },
		{ Category::Herbalist, 1, WriteKind::Stat, "ACW_HERB_Rank_01_Yarrow", "PICK", "HERB_YARROW", 6.000000f, false },
		{ Category::Herbalist, 2, WriteKind::StatDistinct, "ACW_HERB_Rank_02_Berries", "EATEN", "HERB_BLACK_BERRY", 1.000000f, false },
		{ Category::Herbalist, 2, WriteKind::StatDistinct, "ACW_HERB_Rank_02_Berries", "EATEN", "HERB_EVERGREEN_HUCKLEBERRY", 1.000000f, false },
		{ Category::Herbalist, 2, WriteKind::StatDistinct, "ACW_HERB_Rank_02_Berries", "EATEN", "HERB_RED_RASPBERRY", 1.000000f, false },
		{ Category::Herbalist, 2, WriteKind::StatDistinct, "ACW_HERB_Rank_02_Berries", "EATEN", "HERB_WINTERGREEN_BERRY", 1.000000f, false },
		{ Category::Herbalist, 3, WriteKind::StatSum, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_POTENT_HORSE_STIMULANT", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::StatSum, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_SPECIAL_HORSE_STIMULANT_CRAFTED", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::StatSum, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_HORSE_OINTMENT_CRAFTED", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::StatSum, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_POTENT_RESTORATIVE", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::StatSum, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_SPECIAL_RESTORATIVE_CRAFTED", 7.000000f, false },
		{ Category::Herbalist, 3, WriteKind::StatSum, "ACW_HERB_Rank_03_SageCrafting", "MADE", "CONSUMABLE_POTENT_TONIC", 7.000000f, false },
		{ Category::Herbalist, 4, WriteKind::Stat, "ACW_HERB_Rank_04_FeedMushrooms", "", "HORSE_FED_MUSHROOM", 5.000000f, false },
		{ Category::Herbalist, 5, WriteKind::StatSum, "ACW_HERB_Rank_05_TobaccoCrafting", "MADE", "CONSUMABLE_POTENT_SNAKE_OIL", 9.000000f, false },
		{ Category::Herbalist, 5, WriteKind::StatSum, "ACW_HERB_Rank_05_TobaccoCrafting", "MADE", "CONSUMABLE_SPECIAL_SNAKE_OIL_CRAFTED", 9.000000f, false },
		{ Category::Herbalist, 5, WriteKind::StatSum, "ACW_HERB_Rank_05_TobaccoCrafting", "MADE", "CONSUMABLE_POTENT_TONIC", 9.000000f, false },
		// Rank 6 is an IntGroupSum over the "Herbs" PICK group whose template param
		// caps each herb at 1 (allowOverflowProgression=false), so its target of 15 means
		// 15 DIFFERENT herbs picked, not 15 picks (same shape as Horseman rank 10's
		// per-breed goals). One PICK on each of 15 distinct herbs satisfies it. The herb
		// names come from beat_friendly_outdoorsman.ysc.c's func_363 index->name switch
		// (43 herbs total, all used for rank 9 below).
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_YARROW", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_ACUNAS_STAR_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_ALASKAN_GINSENG", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_AMERICAN_GINSENG", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_BAY_BOLETE", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_BLACK_BERRY", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_BLACK_CURRANT", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_BURDOCK_ROOT", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_CHANTERELLES", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_CIGAR_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_CLAMSHELL_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_COMMON_BULRUSH", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_CREEPING_THYME", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_DESERT_SAGE", 1.000000f, false },
		{ Category::Herbalist, 6, WriteKind::StatDistinct, "ACW_HERB_Rank_06_PickingHerbs", "PICK", "HERB_DRAGONS_MOUTH_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 7, WriteKind::Stat, "ACW_HERB_Rank_07_CraftSpecialTonic", "MADE", "CONSUMABLE_SPECIAL_TONIC_CRAFTED", 5.000000f, false },
		{ Category::Herbalist, 7, WriteKind::Stat, "ACW_HERB_Rank_07_UseSpecialTonic", "USED", "SPECIAL_TONIC", 5.000000f, false },
		{ Category::Herbalist, 8, WriteKind::StatSum, "ACW_HERB_Rank_08_PoisonWeapons", "MADE", "AMMO_ARROW_POISON", 6.000000f, false },
		{ Category::Herbalist, 8, WriteKind::StatSum, "ACW_HERB_Rank_08_PoisonWeapons", "MADE", "AMMO_THROWING_KNIVES_POISON", 6.000000f, false },
		// Rank 9 (completeAllParamsInsteadOfGoal): every herb in the group needs PICK >= 1.
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_ACUNAS_STAR_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_ALASKAN_GINSENG", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_AMERICAN_GINSENG", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_BAY_BOLETE", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_BLACK_BERRY", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_BLACK_CURRANT", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_BURDOCK_ROOT", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_CHANTERELLES", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_CIGAR_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_CLAMSHELL_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_COMMON_BULRUSH", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_CREEPING_THYME", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_DESERT_SAGE", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_DRAGONS_MOUTH_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_ENGLISH_MACE", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_EVERGREEN_HUCKLEBERRY", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_GHOST_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_GOLDEN_CURRANT", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_HUMMINGBIRD_SAGE", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_INDIAN_TOBACCO", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_LADY_OF_NIGHT_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_LADY_SLIPPER_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_MILKWEED", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_MOCCASIN_FLOWER_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_NIGHT_SCENTED_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_OLEANDER_SAGE", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_OREGANO", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_PARASOL_MUSHROOM", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_PRAIRIE_POPPY", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_QUEENS_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_RAMS_HEAD", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_RAT_TAIL_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_RED_RASPBERRY", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_RED_SAGE", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_SPARROWS_EGG_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_SPIDER_ORCHID", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_VANILLA_FLOWER", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_VIOLET_SNOWDROP", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_WILD_CARROTS", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_WILD_FEVERFEW", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_WILD_MINT", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_WINTERGREEN_BERRY", 1.000000f, false },
		{ Category::Herbalist, 9, WriteKind::StatDistinct, "ACW_HERB_Rank_09_AllHerbs", "PICK", "HERB_YARROW", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_ExoticBirdSeasoning", "COOKED", "CONSUMABLE_EXOTIC_BIRD_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_ExoticBirdSeasoning", "COOKED", "CONSUMABLE_EXOTIC_BIRD_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_ExoticBirdSeasoning", "COOKED", "CONSUMABLE_EXOTIC_BIRD_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_TenderPorkSeasoning", "COOKED", "CONSUMABLE_TENDER_PORK_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_TenderPorkSeasoning", "COOKED", "CONSUMABLE_TENDER_PORK_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_TenderPorkSeasoning", "COOKED", "CONSUMABLE_TENDER_PORK_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_PlumpBirdSeasoning", "COOKED", "CONSUMABLE_PLUMP_BIRD_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_PlumpBirdSeasoning", "COOKED", "CONSUMABLE_PLUMP_BIRD_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_PlumpBirdSeasoning", "COOKED", "CONSUMABLE_PLUMP_BIRD_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_BigGameMeatSeasoning", "COOKED", "CONSUMABLE_BIG_GAME_MEAT_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_BigGameMeatSeasoning", "COOKED", "CONSUMABLE_BIG_GAME_MEAT_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_BigGameMeatSeasoning", "COOKED", "CONSUMABLE_BIG_GAME_MEAT_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_PrimeBeefSeasoning", "COOKED", "CONSUMABLE_PRIME_BEEF_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_PrimeBeefSeasoning", "COOKED", "CONSUMABLE_PRIME_BEEF_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_PrimeBeefSeasoning", "COOKED", "CONSUMABLE_PRIME_BEEF_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_SucculentFishSeasoning", "COOKED", "CONSUMABLE_SUCCULENT_FISH_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_SucculentFishSeasoning", "COOKED", "CONSUMABLE_SUCCULENT_FISH_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_SucculentFishSeasoning", "COOKED", "CONSUMABLE_SUCCULENT_FISH_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_GameMeatSeasoning", "COOKED", "CONSUMABLE_GAME_MEAT_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_GameMeatSeasoning", "COOKED", "CONSUMABLE_GAME_MEAT_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_GameMeatSeasoning", "COOKED", "CONSUMABLE_GAME_MEAT_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_FlakeyFishSeasoning", "COOKED", "CONSUMABLE_FLAKEY_FISH_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_FlakeyFishSeasoning", "COOKED", "CONSUMABLE_FLAKEY_FISH_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_FlakeyFishSeasoning", "COOKED", "CONSUMABLE_FLAKEY_FISH_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_CrustaceanMeatSeasoning", "COOKED", "CONSUMABLE_CRUSTACEAN_MEAT_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_CrustaceanMeatSeasoning", "COOKED", "CONSUMABLE_CRUSTACEAN_MEAT_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_CrustaceanMeatSeasoning", "COOKED", "CONSUMABLE_CRUSTACEAN_MEAT_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_GristlyMuttonSeasoning", "COOKED", "CONSUMABLE_GRISTLY_MUTTON_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_GristlyMuttonSeasoning", "COOKED", "CONSUMABLE_GRISTLY_MUTTON_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_GristlyMuttonSeasoning", "COOKED", "CONSUMABLE_GRISTLY_MUTTON_THYME_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_MatureVenisonSeasoning", "COOKED", "CONSUMABLE_MATURE_VENISON_WILD_MINT_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_MatureVenisonSeasoning", "COOKED", "CONSUMABLE_MATURE_VENISON_OREGANO_COOKED", 1.000000f, false },
		{ Category::Herbalist, 10, WriteKind::StatSum, "ACW_HERB_Rank_10_MatureVenisonSeasoning", "COOKED", "CONSUMABLE_MATURE_VENISON_THYME_COOKED", 1.000000f, false },
		{ Category::Horseman, 1, WriteKind::Stat, "ACW_HORSE_Rank_01_Rabbits", "KILLED", "AT_RABBIT", 5.000000f, false, Requirement::OnMount },
		{ Category::Horseman, 2, WriteKind::Stat, "ACW_HORSE_Rank_02_Obstacles", "", "HORSE_VAULTS", 3.000000f, false },
		// Ranks 3/6/9 (ACW_HORSE_Rank_{03,06,09}_TimedRide) are
		// StatsGoalPointToPoint goals -- no <scoreParam> at all in
		// goals_sp.meta, and no script anywhere references these goal
		// names, "PointToPoint"/"TimedRide", or either region volume
		// (checked all 1,638 decompiled SP scripts). Every documented
		// native/goal-progress lever was tried and disproven (see this
		// file's header comment). CONFIRMED LIVE 2026-09-17: the real
		// completion check is a native function (sub_140BAC640 in the
		// analyzed build), and the specific goal it's evaluating on any
		// given call is identified by RDX -- WriteKind::PointToPointHook
		// rows store that timed-ride goal index in `value` (reusing the same
		// field other WriteKinds use differently, per KnownWrite's own
		// comment) so TimedRideHook::ScopedTimedRideUnlock can target exactly one
		// goal instead of affecting whichever ones happen to be evaluated
		// in the same tick -- see TimedRideHook.h/.cpp.
		//
		// These RDX values (0x161/0x164/0x167, spacing +3) were discovered via:
		//   1. LML override with marker value (durationSeconds 300->13371337)
		//   2. Cheat Engine "find out what accesses this address"
		//   3. Verified unique across entire ~115MB image via idat.exe+IDAPython
		// If a future game build changes the timed-ride evaluation, these indices
		// may change. Signature scans for sub_140BAC640 and sub_140B9842C are
		// already in place and will report failure if signatures don't match.
		// See TimedRideHook.h/.cpp and CLAUDE.md for full research trail.
		{ Category::Horseman, 3, WriteKind::PointToPointHook, "ACW_HORSE_Rank_03_TimedRide", "", "", 353.000000f, false }, // RDX=0x161
		{ Category::Horseman, 4, WriteKind::StatAtOnce, "ACW_HORSE_Rank_04_LassoDrag", "LONGEST_DIST_DRAGGED", "", 1006.000000f, true, Requirement::OnMount },
		{ Category::Horseman, 5, WriteKind::Stat, "ACW_HORSE_Rank_05_Trample", "KILLS", "ANIMAL", 5.000000f, false },
		{ Category::Horseman, 5, WriteKind::Stat, "ACW_HORSE_Rank_05_Trample", "KILLS", "TRAMPLE", 1.000000f, false },
		{ Category::Horseman, 6, WriteKind::PointToPointHook, "ACW_HORSE_Rank_06_TimedRide", "", "", 356.000000f, false }, // RDX=0x164
		{ Category::Horseman, 7, WriteKind::Stat, "ACW_HORSE_Rank_07_KillNoDismount", "KILLS", "ENEMY", 7.000000f, false, Requirement::OnMount },
		{ Category::Horseman, 8, WriteKind::Stat, "ACW_HORSE_Rank_08_Predators", "KILLS", "PREDATOR", 9.000000f, false, Requirement::OnMount },
		{ Category::Horseman, 9, WriteKind::PointToPointHook, "ACW_HORSE_Rank_09_TimedRide", "", "", 359.000000f, false }, // RDX=0x167
		// Rank 10 requires ALL 9 of these goals (challenges_sp.meta lists
		// them together under one rank's <goalHashes>, not as alternatives --
		// Arabian is commented out in the real file, so only 9 breeds are
		// actually required). Each goal's only scoreParam leaf is a
		// StatsGoalScoreSourceCompendium (e.g. CMPNDM_AMPAINT/_RARE for the
		// Paint goal), which kKnownWrites' generator never emitted a row for
		// (Stat/Script leaves only) -- see this file's header comment and
		// CLAUDE.md's coverage table. Fixed 2026-09-18: the real script
		// (player_horse.ysc.c) marks a breed's compendium entry "broken" by
		// calling COMPENDIUM::COMPENDIUM_HORSE_WILD_BROKEN(pedIndex) on the
		// wild horse ped just tamed -- the native reads the ped's own model
		// to figure out which breed/entry to credit, so WriteKind::HorseCompendium
		// spawns a short-lived ped of each breed's model, calls the native on
		// it, then deletes it. modelHash values are the real breed ped model
		// hashes (not joaat of the English breed name -- verified those don't
		// match; these came from the user's own data pull).
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_American_Paint", "", "", 0.0f, false, Requirement::None, 0xE52CB9B2 },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_American_Standardbred", "", "", 0.0f, false, Requirement::None, 0xED07737A },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Appaloosa", "", "", 0.0f, false, Requirement::None, 0x7EF6A7DC },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Hungarian", "", "", 0.0f, false, Requirement::None, 0x65A30467 },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Kentucky", "", "", 0.0f, false, Requirement::None, 0xA5A0532E },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Morgan", "", "", 0.0f, false, Requirement::None, 0x4955CBE3 },
		// modelHash here is a_c_horse_mustang_wildbay, NOT the earlier
		// A_C_HORSE_MUSTANG_BUCKSKIN (0x62121AEC) -- live-tested 2026-09-1{8,9}
		// and DISPROVEN: the native ran without error (log line printed) but
		// never actually marked CMPNDM_MUSTANG/_RARE broken. Buckskin never
		// once appears among the wild-population coat switch cases any
		// decompiled SP script uses for Mustang (grullodun/tigerstripedbay/
		// goldendun/wildbay are the only 4 -- confirmed by grepping all 1,638
		// scripts) -- it's a stable-purchase-only coat, not one the ambient
		// wild population (or COMPENDIUM_HORSE_WILD_BROKEN's own internal
		// wild-coat table) recognizes as a legitimate "wild" Mustang. Picked
		// wildbay (appears as the sole/default case in several scripts,
		// e.g. ambush_bnd_cliff1.ysc.c) as a real wild coat instead.
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Mustang", "", "", 0.0f, false, Requirement::None, 0x7E4DF66E },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Nokota", "", "", 0.0f, false, Requirement::None, 0x0660E640 },
		{ Category::Horseman, 10, WriteKind::HorseCompendium, "ACW_HORSE_Rank_10_Tennessee", "", "", 0.0f, false, Requirement::None, 0x400B3937 },
		{ Category::MasterHunter, 1, WriteKind::StatSum, "ACW_HUNT_Rank_01_Skin", "SKINNED", "AT_DEER", 3.000000f, false },
		{ Category::MasterHunter, 1, WriteKind::StatSum, "ACW_HUNT_Rank_01_Skin", "SKINNED", "AT_BUCK", 3.000000f, false },
		{ Category::MasterHunter, 1, WriteKind::StatSum, "ACW_HUNT_Rank_01_Skin", "SKINNED", "AT_BUCK_LEGENDARY", 3.000000f, false },
		{ Category::MasterHunter, 2, WriteKind::ScriptGoal, "ACW_HUNT_Rank_02_Rabbits", "", "", 3.000000f, false },
		{ Category::MasterHunter, 4, WriteKind::Stat, "ACW_HUNT_Rank_04_CleanKill", "KILLS", "ANIMAL_RESPONDING_TO_CALL", 5.000000f, false },
		// Master Hunter rank 3 is an IntGroupSum over the TRACKED/ANIMALS stat group whose
		// template caps each animal at 1, so its target of 10 means 10 DIFFERENT animals
		// tracked (same shape as Herbalist rank 6), gated on CHAL_CTX_SCOPED_KIT. The
		// group's membership isn't defined in either meta file; these are common
		// AT_<animal> permutations (the naming the game's scripts use), 12 of them so a
		// wrong guess or two can't leave the sum under 10.
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_DEER", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_ELK", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_BOAR", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_COUGAR", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_WOLF", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_FOX", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_PRONGHORN", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_BUCK", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_RABBIT", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_RACCOON", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_SQUIRREL", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 3, WriteKind::StatDistinct, "ACW_HUNT_Rank_03_Binoculars", "TRACKED", "AT_TURKEY", 1.000000f, false, Requirement::ScopedKit },
		{ Category::MasterHunter, 5, WriteKind::StatSum, "ACW_HUNT_Rank_05_Bear", "SKINNED", "AT_BEAR_GRIZZLY", 3.000000f, false },
		{ Category::MasterHunter, 5, WriteKind::StatSum, "ACW_HUNT_Rank_05_Bear", "SKINNED", "AT_BEAR_LEGENDARY", 3.000000f, false },
		{ Category::MasterHunter, 5, WriteKind::StatSum, "ACW_HUNT_Rank_05_Bear", "SKINNED", "AT_BEAR_BLACK", 3.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::StatSum, "ACW_HUNT_Rank_06_CougarKill", "KILLED", "AT_COUGAR", 5.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::StatSum, "ACW_HUNT_Rank_06_CougarKill", "KILLED", "AT_COUGAR_LEGENDARY", 5.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::Stat, "ACW_HUNT_Rank_06_CougarKill", "KILLS", "SN_BOW", 1.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::StatSum, "ACW_HUNT_Rank_06_CougarSkin", "SKINNED", "AT_COUGAR", 5.000000f, false },
		{ Category::MasterHunter, 6, WriteKind::StatSum, "ACW_HUNT_Rank_06_CougarSkin", "SKINNED", "AT_COUGAR_LEGENDARY", 5.000000f, false },
		{ Category::MasterHunter, 7, WriteKind::StatDistinct, "ACW_HUNT_Rank_07_BaitedKills", "KILLS", "ANIMAL_HERBIVORE_BAITED", 1.000000f, false },
		{ Category::MasterHunter, 7, WriteKind::StatDistinct, "ACW_HUNT_Rank_07_BaitedKills", "KILLS", "ANIMAL_PREDATOR_BAITED", 1.000000f, false },
		{ Category::MasterHunter, 8, WriteKind::Stat, "ACW_HUNT_Rank_08_LootedFish", "LOOTED", "FISH", 3.000000f, false },
		{ Category::MasterHunter, 9, WriteKind::Stat, "ACW_HUNT_Rank_09_Possum", "KILLED_WHILST_PLAYING_DEAD", "AT_POSSUM", 1.000000f, false },
		{ Category::MasterHunter, 10, WriteKind::Stat, "ACW_HUNT_Rank_10_Panther", "KILLED", "AT_PANTHER_LEGENDARY", 1.000000f, false },
		// Sharpshooter ranks 1 and 3 bind FLYING_BIRD kills to KILLED/AT_BAT with
		// CHECK_FOR_SCORE_WHEN_BIND_NOT_PROGRESS: the bird score is only checked
		// while the bat stat is NOT moving (bat kills are excluded). The generator
		// emitted the bat stat as a write like any other leaf, which suppressed
		// the check every time -- so it is deliberately omitted here.
		{ Category::Sharpshooter, 1, WriteKind::Stat, "ACW_SHOT_Rank_01_Flying", "KILLS", "FLYING_BIRD", 3.000000f, false },
		{ Category::Sharpshooter, 1, WriteKind::Stat, "ACW_SHOT_Rank_01_Flying", "KILLS", "SHOOTING", 1.000000f, false },
		// Sharpshooter rank 2: kill 2 DIFFERENT animals within one Dead Eye activation. A
		// KILLED/ANIMALS group sum (template capped at 1 per animal, target 2), bound to
		// KILLS/DEADEYE progressing (checked only when it moves), and reset whenever
		// SPECIAL_ABILITY_ACTIVE_NUM/DEACTIVE_NUM changes -- so Dead Eye must already be on
		// (gated below) and we never toggle it. The group's membership isn't in the meta
		// files; these are common AT_<animal> names, 4 so a wrong guess can't leave it under 2.
		{ Category::Sharpshooter, 2, WriteKind::Stat, "ACW_SHOT_Rank_02_Animals", "KILLS", "DEADEYE", 1.000000f, false, Requirement::DeadeyeActive },
		{ Category::Sharpshooter, 2, WriteKind::StatDistinct, "ACW_SHOT_Rank_02_Animals", "KILLED", "AT_DEER", 1.000000f, false, Requirement::DeadeyeActive },
		{ Category::Sharpshooter, 2, WriteKind::StatDistinct, "ACW_SHOT_Rank_02_Animals", "KILLED", "AT_RABBIT", 1.000000f, false, Requirement::DeadeyeActive },
		{ Category::Sharpshooter, 2, WriteKind::StatDistinct, "ACW_SHOT_Rank_02_Animals", "KILLED", "AT_ELK", 1.000000f, false, Requirement::DeadeyeActive },
		{ Category::Sharpshooter, 2, WriteKind::StatDistinct, "ACW_SHOT_Rank_02_Animals", "KILLED", "AT_BOAR", 1.000000f, false, Requirement::DeadeyeActive },
		{ Category::Sharpshooter, 3, WriteKind::Stat, "ACW_SHOT_Rank_03_Train", "KILLS", "FLYING_BIRD", 5.000000f, false, Requirement::OnMovingTrain },
		{ Category::Sharpshooter, 4, WriteKind::StatAtOnce, "ACW_SHOT_Rank_04_Tomahawk", "FURTHEST_KILL", "TH_TOMAHAWK", 24.500000f, true },
		{ Category::Sharpshooter, 4, WriteKind::Stat, "ACW_SHOT_Rank_04_Tomahawk", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::Sharpshooter, 5, WriteKind::Stat, "ACW_SHOT_Rank_05_Switching", "KILLS", "ANIMAL", 6.000000f, false },
		{ Category::Sharpshooter, 5, WriteKind::Stat, "ACW_SHOT_Rank_05_Switching", "KILLS", "GUN", 1.000000f, false },
		{ Category::Sharpshooter, 6, WriteKind::StatAtOnce, "ACW_SHOT_Rank_06_ScopedRifle", "FURTHEST_KILL", "", 201.199997f, true },
		{ Category::Sharpshooter, 6, WriteKind::Stat, "ACW_SHOT_Rank_06_ScopedRifle", "KILLS", "GROUP_SNIPER", 1.000000f, false },
		{ Category::Sharpshooter, 6, WriteKind::Stat, "ACW_SHOT_Rank_06_ScopedRifle", "KILLS", "HUMAN", 1.000000f, false },
		{ Category::Sharpshooter, 7, WriteKind::Stat, "ACW_SHOT_Rank_07_Headshots", "STREAK", "HEADSHOT", 7.000000f, false },
		{ Category::Sharpshooter, 8, WriteKind::Stat, "ACW_SHOT_Rank_08_Disarm", "DISARMS", "", 3.000000f, false },
		{ Category::Sharpshooter, 9, WriteKind::Stat, "ACW_SHOT_Rank_09_Disarm", "HATSHOTS", "", 3.000000f, false, Requirement::DeadeyeActive },
		{ Category::Sharpshooter, 10, WriteKind::Stat, "ACW_SHOT_Rank_10_SniperRifle", "KILLS", "FLYING_BIRD", 3.000000f, false },
		{ Category::Sharpshooter, 10, WriteKind::Stat, "ACW_SHOT_Rank_10_SniperRifle", "KILLS", "GROUP_SNIPER", 1.000000f, false },
		{ Category::Survivalist, 1, WriteKind::StatSum, "ACW_SURV_Rank_01_Bluegill", "CAUGHT", "AT_FBLUEGIL", 3.000000f, false },
		{ Category::Survivalist, 1, WriteKind::StatSum, "ACW_SURV_Rank_01_Bluegill", "CAUGHT", "AT_FBLUEGILL_LEGENDARY", 3.000000f, false },
		{ Category::Survivalist, 2, WriteKind::Stat, "ACW_SURV_Rank_02_CarcassDonation", "CARCASSES_DONATED", "", 5.000000f, false },
		{ Category::Survivalist, 3, WriteKind::Stat, "ACW_SURV_Rank_03_VarmintRifle", "KILLS", "RF_VARMINT", 5.000000f, false },
		{ Category::Survivalist, 3, WriteKind::Stat, "ACW_SURV_Rank_03_VarmintRifle", "KILLS", "ANIMAL", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_DynamiteArrow", "MADE", "AMMO_ARROW_DYNAMITE", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_FireArrow", "MADE", "AMMO_ARROW_FIRE", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_ImprovedArrow", "MADE", "AMMO_ARROW_IMPROVED", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_PoisonArrow", "MADE", "AMMO_ARROW_POISON", 1.000000f, false },
		{ Category::Survivalist, 4, WriteKind::Stat, "ACW_SURV_Rank_04_SmallGameArrow", "MADE", "AMMO_ARROW_SMALL_GAME", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "CANOE", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "PIROGUE", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "ROWBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "ROWBOATSWAMP", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "SKIFF", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "GUAMABOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "HORSEBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "KEELBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "RCBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "STEAMBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "TUGBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::StatSum, "ACW_SURV_Rank_05_FishingRiverboat", "FISH_CAUGHT_IN", "TURBINEBOAT", 1.000000f, false },
		{ Category::Survivalist, 5, WriteKind::Stat, "ACW_SURV_Rank_05_FishingTracks", "FISH_CAUGHT_ON_TRAIN_TRACKS", "", 1.000000f, false },
		{ Category::Survivalist, 6, WriteKind::Stat, "ACW_SURV_Rank_06_ScavengerKill", "KILLS", "SCAVENGING_ANIMAL", 5.000000f, false },
		{ Category::Survivalist, 7, WriteKind::Stat, "ACW_SURV_Rank_07_SmallGame", "KILLS", "SMALL_ANIMALS", 8.000000f, false },
		{ Category::Survivalist, 7, WriteKind::Stat, "ACW_SURV_Rank_07_SmallGame", "KILLS", "AMMO_ARROW_SMALL_GAME", 1.000000f, false },
		{ Category::Survivalist, 8, WriteKind::Stat, "ACW_SURV_Rank_08_HomingTomahawk", "MADE", "AMMO_TOMAHAWK_HOMING", 1.000000f, false },
		{ Category::Survivalist, 8, WriteKind::Stat, "ACW_SURV_Rank_08_ImprovedTomahawk", "MADE", "AMMO_TOMAHAWK_IMPROVED", 1.000000f, false },
		{ Category::Survivalist, 8, WriteKind::Stat, "ACW_SURV_Rank_08_VolatileDynamite", "MADE", "AMMO_DYNAMITE_VOLATILE", 1.000000f, false },
		{ Category::Survivalist, 8, WriteKind::Stat, "ACW_SURV_Rank_08_VolatileFireBottle", "MADE", "AMMO_MOLOTOV_VOLATILE", 1.000000f, false },
		{ Category::Survivalist, 9, WriteKind::StatAtOnce, "ACW_SURV_Rank_09_HeavyFishCaught", "BIGGEST_FISH_CAUGHT", "", 19.000000f, true },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_Bluegill", "CAUGHT", "AT_FBLUEGIL", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_Bluegill", "CAUGHT", "AT_FBLUEGILL_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_BullheadCatfish", "CAUGHT", "AT_FBULLHEADCATFISH", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_BullheadCatfish", "CAUGHT", "AT_FBULLHEAD_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_ChainPickerel", "CAUGHT", "AT_FCHAINPICKEREL", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_ChainPickerel", "CAUGHT", "AT_FPICKEREL_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::Stat, "ACW_SURV_Rank_10_ChannelCatfish", "CAUGHT", "AT_FCHANNELCATFISH", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_LakeSturgeon", "CAUGHT", "AT_FLAKESTURGEON", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_LakeSturgeon", "CAUGHT", "AT_FSTURGEON_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_LargemouthBass", "CAUGHT", "AT_FLARGEMOUTHBASS", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_LargemouthBass", "CAUGHT", "AT_FLGBASS_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_LongnoseGar", "CAUGHT", "AT_FLONGNOSEGAR", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_LongnoseGar", "CAUGHT", "AT_FGAR_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_Muskie", "CAUGHT", "AT_FMUSKIE", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_Muskie", "CAUGHT", "AT_FMUSKIE_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_NorthernPike", "CAUGHT", "AT_FNORTHERNPIKE", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_NorthernPike", "CAUGHT", "AT_FPIKE_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_Perch", "CAUGHT", "AT_FPERCH", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_Perch", "CAUGHT", "AT_FPERCH_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_RedfinPickerel", "CAUGHT", "AT_FREDFINPICKEREL", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_RedfinPickerel", "CAUGHT", "AT_FREDFIN_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_RockBass", "CAUGHT", "AT_FROCKBASS", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_RockBass", "CAUGHT", "AT_FROCKBASS_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_SmallmouthBass", "CAUGHT", "AT_FSMALLMOUTHBASS", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_SmallmouthBass", "CAUGHT", "AT_FSMBASS_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_SockeyeSalmon", "CAUGHT", "AT_FSALMONSOCKEYE", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_SockeyeSalmon", "CAUGHT", "AT_FSALMON_LEGENDARY", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_SteelheadTrout", "CAUGHT", "AT_FRAINBOWTROUT", 1.000000f, false },
		{ Category::Survivalist, 10, WriteKind::StatSum, "ACW_SURV_Rank_10_SteelheadTrout", "CAUGHT", "AT_FTROUT_LEGENDARY", 1.000000f, false },
		{ Category::WeaponsExpert, 1, WriteKind::Stat, "ACW_WEAP_Rank_01_KnifeKills", "KILLS", "KNIFE", 3.000000f, false },
		{ Category::WeaponsExpert, 1, WriteKind::Stat, "ACW_WEAP_Rank_01_KnifeKills", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 2, WriteKind::Stat, "ACW_WEAP_Rank_02_ThrowingKnife", "KILLS", "TH_KNIVES", 3.000000f, false },
		{ Category::WeaponsExpert, 3, WriteKind::Stat, "ACW_WEAP_Rank_03_Tomahawk", "KILLS", "BIRDS_OF_PREY", 3.000000f, false },
		{ Category::WeaponsExpert, 3, WriteKind::Stat, "ACW_WEAP_Rank_03_Tomahawk", "KILLS", "TH_TOMAHAWK", 1.000000f, false },
		{ Category::WeaponsExpert, 4, WriteKind::StatSum, "ACW_WEAP_Rank_04_ShotgunCraftedAmmo", "KILLS", "AMMO_SHOTGUN_BUCKSHOT_INCENDIARY", 10.000000f, false },
		{ Category::WeaponsExpert, 4, WriteKind::StatSum, "ACW_WEAP_Rank_04_ShotgunCraftedAmmo", "KILLS", "AMMO_SHOTGUN_SLUG_EXPLOSIVE", 10.000000f, false },
		{ Category::WeaponsExpert, 4, WriteKind::Stat, "ACW_WEAP_Rank_04_ShotgunCraftedAmmo", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 5, WriteKind::Stat, "ACW_WEAP_Rank_05_Mounted", "KILLS", "MOUNTED_PED", 5.000000f, false },
		{ Category::WeaponsExpert, 5, WriteKind::Stat, "ACW_WEAP_Rank_05_Mounted", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 5, WriteKind::Stat, "ACW_WEAP_Rank_05_Mounted", "KILLS", "TH_KNIVES", 1.000000f, false },
		{ Category::WeaponsExpert, 5, WriteKind::Stat, "ACW_WEAP_Rank_05_Mounted", "KILLS", "ONE_SHOT", 1.000000f, false },
		{ Category::WeaponsExpert, 6, WriteKind::StatAtOnce, "ACW_WEAP_Rank_06_Dynamite", "KILLS", "ENEMY", 4.000000f, false },
		{ Category::WeaponsExpert, 6, WriteKind::StatAtOnce, "ACW_WEAP_Rank_06_Dynamite", "KILLS", "TH_DYNAMITE", 1.000000f, false },
		{ Category::WeaponsExpert, 7, WriteKind::StatAtOnce, "ACW_WEAP_Rank_07_Tomahawk", "KILLS", "FROM_RECENT_PICKUP", 4.000000f, false },
		{ Category::WeaponsExpert, 7, WriteKind::StatAtOnce, "ACW_WEAP_Rank_07_Tomahawk", "KILLS", "TH_TOMAHAWK", 1.000000f, false },
		{ Category::WeaponsExpert, 7, WriteKind::StatAtOnce, "ACW_WEAP_Rank_07_Tomahawk", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 8, WriteKind::Stat, "ACW_WEAP_Rank_08_Sidearm", "KILLS", "CI_TAG_LONG_BARRELED_SIDEARM", 15.000000f, false },
		{ Category::WeaponsExpert, 9, WriteKind::Stat, "ACW_WEAP_Rank_09_Bow", "KILLS", "FROM_BEHIND", 9.000000f, false },
		{ Category::WeaponsExpert, 9, WriteKind::Stat, "ACW_WEAP_Rank_09_Bow", "KILLS", "UNAWARE", 1.000000f, false },
		{ Category::WeaponsExpert, 9, WriteKind::Stat, "ACW_WEAP_Rank_09_Bow", "KILLS", "ENEMY", 1.000000f, false },
		{ Category::WeaponsExpert, 9, WriteKind::Stat, "ACW_WEAP_Rank_09_Bow", "KILLS", "SN_BOW", 1.000000f, false },
		{ Category::WeaponsExpert, 10, WriteKind::Stat, "ACW_WEAP_Rank_10_Bear", "KILLED", "AT_BEAR_GRIZZLY", 1.000000f, false },
		{ Category::WeaponsExpert, 10, WriteKind::Stat, "ACW_WEAP_Rank_10_Bear", "KILLS", "NO_DAMAGE_RECEIVED", 1.000000f, false },
		{ Category::WeaponsExpert, 10, WriteKind::StatSum, "ACW_WEAP_Rank_10_Bear", "KILLS", "TH_KNIVES", 1.000000f, false },
		{ Category::WeaponsExpert, 10, WriteKind::Stat, "ACW_WEAP_Rank_10_Bear", "KILLS", "ONE_WEAPON", 1.000000f, false },
	};

	constexpr int kMaxRank = 10;

	// Empty for any rank outside 1-kMaxRank: `rank` comes from the game's
	// CHAL_* natives, which aren't guaranteed to stay within the table.
	const std::vector<const KnownWrite*>& RankWritesFor(Category category, int rank)
	{
		static std::array<std::array<std::vector<const KnownWrite*>, kMaxRank + 1>, static_cast<std::size_t>(Category::Count)> writeLookup{};
		static const std::vector<const KnownWrite*> kNone;
		static bool initialized = false;
		if (!initialized)
		{
			for (const auto& write : kKnownWrites)
			{
				writeLookup[static_cast<std::size_t>(write.category)][write.rank].push_back(&write);
			}
			initialized = true;
		}
		if (rank < 1 || rank > kMaxRank || category < Category::Bandit || category >= Category::Count)
			return kNone;
		return writeLookup[static_cast<std::size_t>(category)][rank];
	}

	// Horseman rank 10's 9 goals each only ever check whether a specific
	// breed's compendium entry has been marked "broken" -- there's no
	// persisted counter or stat behind it at all (see kKnownWrites' own
	// comment above the rank-10 rows). The real script (player_horse.ysc.c,
	// ~line 6546) does this by calling
	// COMPENDIUM::COMPENDIUM_HORSE_WILD_BROKEN(pedIndex) on the wild horse
	// ped that was just tamed -- the native reads THAT ped's own model to
	// figure out which breed's entry to credit, it isn't told the breed
	// directly. So this spawns a short-lived, no-longer-needed ped of the
	// requested breed's model a few meters from the player, calls the
	// native on it once, then deletes it immediately -- the player never
	// sees it appear.
	void (*g_waitDrawCallback)() = nullptr;

	// WAIT(ms) that keeps the menu on screen (see SetWaitDrawCallback()).
	void WaitAndDraw(int ms)
	{
		const ULONGLONG end = GetTickCount64() + static_cast<ULONGLONG>(ms);
		do
		{
			WAIT(0);
			if (g_waitDrawCallback)
				g_waitDrawCallback();
		} while (GetTickCount64() < end);
	}

	bool SpawnAndBreakCompendiumHorse(Hash modelHash, std::string_view label)
	{
		if (!STREAMING::IS_MODEL_IN_CDIMAGE(modelHash) || !STREAMING::IS_MODEL_VALID(modelHash))
		{
			Log::Write("SpawnAndBreakCompendiumHorse: model {:#x} for goal '{}' is not a valid/streamable "
				"model in this build.", modelHash, label);
			return false;
		}

		STREAMING::REQUEST_MODEL(modelHash, false);
		for (int attempt = 0; attempt < 100 && !STREAMING::HAS_MODEL_LOADED(modelHash); attempt++)
			WaitAndDraw(50);

		if (!STREAMING::HAS_MODEL_LOADED(modelHash))
		{
			Log::Write("SpawnAndBreakCompendiumHorse: model {:#x} for goal '{}' never finished loading "
				"after 5s.", modelHash, label);
			STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(modelHash);
			return false;
		}

		Ped playerPed = PLAYER::PLAYER_PED_ID();

		// Defensive check -- in singleplayer with a valid player, this should never be 0
		if (playerPed == 0)
		{
			Log::Write("SpawnAndBreakCompendiumHorse: PLAYER_PED_ID() returned invalid ped for goal '{}'",
				label);
			STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(modelHash);
			return false;
		}

		Vector3 coords = ENTITY::GET_ENTITY_COORDS(playerPed, true, true);
		// A few meters off to the side is enough to avoid spawning inside
		// the player; exact placement doesn't matter since this ped is
		// deleted again within the same call, before a render frame.
		Ped horse = PED::CREATE_PED(modelHash, coords.x + 3.0f, coords.y + 3.0f, coords.z, 0.0f, false, true, false, false);
		STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(modelHash);

		if (!ENTITY::DOES_ENTITY_EXIST(horse))
		{
			Log::Write("SpawnAndBreakCompendiumHorse: CREATE_PED failed for goal '{}' (model {:#x}).",
				label, modelHash);
			return false;
		}

		COMPENDIUM::COMPENDIUM_HORSE_WILD_BROKEN(horse);
		Log::Write("SpawnAndBreakCompendiumHorse: called COMPENDIUM_HORSE_WILD_BROKEN on a spawned ped "
			"for goal '{}' (model {:#x}).", label, modelHash);

		ENTITY::SET_ENTITY_AS_MISSION_ENTITY(horse, true, true);
		PED::DELETE_PED(&horse);
		return true;
	}

	std::string g_lastFailureReason;
}

namespace ChallengeCheat
{
	std::string_view GetDisplayName(Category category)
	{
		return Localization::CategoryName(static_cast<int>(category));
	}

	void SetWaitDrawCallback(void (*callback)())
	{
		g_waitDrawCallback = callback;
	}

	void ResetSessionState()
	{
		if (!g_distinctStepsCredited.empty())
			Log::Write("ResetSessionState: loading screen seen -- forgetting {} per-goal Advance step counter(s)", g_distinctStepsCredited.size());
		g_distinctStepsCredited.clear();
	}

	const std::string& GetLastAdvanceFailureReason()
	{
		return g_lastFailureReason;
	}

	RankInfo GetRankInfo(Category category)
	{
		const Hash rootHash = RootHash(category);
		return { STATS::CHAL_GET_NUM_RANKS_COMPLETED(rootHash), STATS::CHAL_GET_MAX_RANKS(rootHash) };
	}

	int GetRanksCompleted(Category category)
	{
		return GetRankInfo(category).completed;
	}

	int GetMaxRanks(Category category)
	{
		return GetRankInfo(category).max;
	}

	// Shared implementation behind both AdvanceRank() (WriteMode::Step) and
	// CompleteChallenge() (WriteMode::Complete). Fire-and-forget by design
	// (2026-09-19): does NOT poll CHAL_GET_NUM_RANKS_COMPLETED before
	// reporting success. An earlier version did poll for ~3s and reported
	// failure if the counter hadn't moved yet -- live testing showed this
	// was actively wrong, not just slow: writes that were genuinely
	// completing the rank (visible on screen moments later) still got
	// reported as "could not advance" because the challenge system's own
	// re-evaluation regularly takes longer than the poll window. A Step-mode
	// call is ALSO frequently not expected to complete the rank at all (that
	// is the point of a step), so a rank-counter check was never the right
	// success signal for this mode either. Returns true whenever at least
	// one write was actually applied; false only when nothing could be
	// attempted at all (already maxed, a live requirement gate blocks it, or
	// the goal has no known mechanism) -- ALWAYS with g_lastFailureReason
	// set in that case, since that's the only situation worth telling the
	// player about on screen.
	bool ApplyRankProgress(Category category, WriteMode mode)
	{
		g_lastFailureReason.clear();
		const std::string_view verb = (mode == WriteMode::Step) ? "AdvanceRank" : "CompleteChallenge";

		Hash chalHash = RootHash(category);
		int before = STATS::CHAL_GET_NUM_RANKS_COMPLETED(chalHash);
		int maxRanks = STATS::CHAL_GET_MAX_RANKS(chalHash);

		if (before >= maxRanks)
		{
			g_lastFailureReason.assign(Localization::Text(Localization::Msg::AlreadyCompleted))
				.append(" (").append(std::to_string(before)).append("/").append(std::to_string(maxRanks)).append(").");
			Log::Write("{}({}): already at max rank ({}/{})", verb, Info(category).displayName, before, maxRanks);
			return false;
		}

		int targetRank = before + 1;

		// Pre-check live requirements BEFORE writing anything for this rank
		// -- live-CONFIRMED (2026-09-17, Horseman rank 1) that a goal's
		// AIConditional wrapper can be a real runtime gate: writing
		// KILLED/AT_RABBIT to 5 did nothing until the player was actually
		// on horseback when the write happened. Checking Requirement::OnMount
		// up front avoids burning a write on an attempt that's guaranteed to
		// fail, and tells the player exactly what to do instead of a bare
		// "didn't work."
		const auto& rankWrites = RankWritesFor(category, targetRank);
		for (const auto* w : rankWrites)
		{
			const auto& write = *w;
			if (write.requirement == Requirement::OnMount && !PED::IS_PED_ON_MOUNT(PLAYER::PLAYER_PED_ID()))
			{
				g_lastFailureReason = Localization::Text(Localization::Msg::NeedHorseback);
				Log::Write("{}({}): rank {}'s goal '{}' requires being on horseback -- "
					"mount up and try again. No change made.",
					verb, Info(category).displayName, targetRank, write.label);
				return false;
			}
			if (write.requirement == Requirement::OnMovingTrain && !PLAYER::IS_PLAYER_RIDING_TRAIN(PLAYER::PLAYER_ID()))
			{
				g_lastFailureReason = Localization::Text(Localization::Msg::NeedTrain);
				Log::Write("{}({}): rank {}'s goal '{}' requires riding a train -- "
					"hop aboard and try again. No change made.",
					verb, Info(category).displayName, targetRank, write.label);
				return false;
			}
			if (write.requirement == Requirement::ScopedKit && !SCRIPT::_IS_GOAL_CONTEXT_ACTIVE(static_cast<Hash>(rage::Joaat("CHAL_CTX_SCOPED_KIT"))))
			{
				g_lastFailureReason = Localization::Text(Localization::Msg::NeedBinoculars);
				Log::Write("{}({}): rank {}'s goal '{}' requires the scoped-kit context (binoculars/scope up) -- "
					"not active. No change made.",
					verb, Info(category).displayName, targetRank, write.label);
				return false;
			}
			if (write.requirement == Requirement::DeadeyeActive)
			{
				// The game only keeps Dead Eye on while aiming a weapon, and forcing
				// it from script drops right back off (live-tested), so the player
				// has to aim and activate it themselves before clicking.
				const Player player = PLAYER::PLAYER_ID();
				if (!PLAYER::IS_PLAYER_FREE_AIMING(player) && !CAMERA::IS_AIM_CAM_ACTIVE())
				{
					g_lastFailureReason = Localization::Text(Localization::Msg::NeedDeadEyeAiming);
					Log::Write("{}({}): rank {}'s goal '{}' requires aiming with Dead Eye active -- "
						"not aiming. No change made.",
						verb, Info(category).displayName, targetRank, write.label);
					return false;
				}
				if (!PLAYER::_IS_SPECIAL_ABILITY_ACTIVE(player))
				{
					g_lastFailureReason = Localization::Text(Localization::Msg::NeedDeadEye);
					Log::Write("{}({}): rank {}'s goal '{}' requires Dead Eye to be active -- "
						"activate it and try again. No change made.",
						verb, Info(category).displayName, targetRank, write.label);
					return false;
				}
			}
		}

		// A challenge category is hidden/locked until the story reaches it (real
		// scripts call UNLOCK_SET_VISIBLE / UNLOCK_SET_UNLOCKED on the root at
		// specific story checkpoints -- e.g. Survivalist stays hidden on a new
		// game until then), and its goals aren't active while it is. Writes to a
		// hidden category's goals do nothing, so reveal and unlock it first.
		{
			const bool wasVisible = UNLOCK::UNLOCK_IS_VISIBLE(chalHash) != FALSE;
			const bool wasUnlocked = UNLOCK::UNLOCK_IS_UNLOCKED(chalHash) != FALSE;
			if (!wasVisible || !wasUnlocked)
			{
				UNLOCK::UNLOCK_SET_VISIBLE(chalHash, TRUE);
				UNLOCK::UNLOCK_SET_UNLOCKED(chalHash, TRUE);
				Log::Write("{}({}): category was {}{}{} -- made it visible and unlocked; waiting a moment for its goals to activate.",
					verb, Info(category).displayName,
					wasVisible ? "" : "hidden", (!wasVisible && !wasUnlocked) ? " and " : "", wasUnlocked ? "" : "locked");
				WaitAndDraw(250);
			}
		}

		// Diagnostics: what the game itself thinks of this rank's goals right now,
		// logged before every write so a "did nothing" report can be told apart
		// from "goal wasn't even active" without another build.
		{
			std::unordered_set<std::string_view> seenLabels; // views of static table literals
			for (const auto* w : rankWrites)
			{
				const auto& write = *w;
				if (seenLabels.insert(write.label).second == false)
					continue;
				Log::Write("{}({}): rank counter={}/{}, goal '{}' active={}",
					verb, Info(category).displayName,
					STATS::CHAL_GET_NUM_RANKS_COMPLETED(chalHash), STATS::CHAL_GET_MAX_RANKS(chalHash),
					write.label, STATS::CHAL_IS_GOAL_ACTIVE(chalHash, static_cast<Hash>(rage::Joaat(write.label))) != FALSE);
			}
		}

		// Horseman rank 10 (HorseCompendium) Step: if the game reports some of
		// the rank's per-breed goals active and some not, that tells us
		// exactly which breeds are still needed. If it reports them all the
		// same (can't tell), fall back to our own per-rank counter.
		bool compendiumGoalStateUsable = false;
		if (mode == WriteMode::Step)
		{
			int total = 0;
			int active = 0;
			for (const auto* w : rankWrites)
			{
				const auto& write = *w;
				if (write.kind != WriteKind::HorseCompendium)
					continue;
				++total;
				const bool isActive = STATS::CHAL_IS_GOAL_ACTIVE(chalHash, static_cast<Hash>(rage::Joaat(write.label))) != FALSE;
				if (isActive)
					++active;
				Log::Write("{}({}): goal '{}' active={}", verb, Info(category).displayName, write.label, isActive);
			}
			compendiumGoalStateUsable = active > 0 && active < total;
			if (total > 0)
				Log::Write("{}({}): {} of {} per-breed goals report active -- using {} to pick the next breed.",
					verb, Info(category).displayName, active, total,
					compendiumGoalStateUsable ? "the game's own goal state" : "our own step counter (goal state didn't distinguish them)");
		}

		int appliedCount = 0;
		bool sawDistinctStep = false;
		bool distinctStepDone = false;
		std::string_view distinctRowLabel;
		int distinctRowIndex = 0;
		int compendiumRowIndex = 0;
		std::unordered_set<std::string_view> steppedSumGoals;
		for (const auto* w : rankWrites)
		{
			const auto& write = *w;
			if (write.kind == WriteKind::Stat || write.kind == WriteKind::StatSum || write.kind == WriteKind::StatDistinct || write.kind == WriteKind::StatAtOnce)
			{
				StatId id{
					static_cast<Hash>(rage::Joaat(write.baseId)),
					static_cast<Hash>(rage::Joaat(write.permId))
				};
				// Real script call sites (e.g. dominoes_sp.ysc.c's func_606)
				// only ever use _STAT_ID_INCREMENT_INT/_FLOAT for progress --
				// never STAT_ID_SET_INT/_FLOAT, which a live test showed does
				// NOT move the challenge rank counter even with a correct,
				// real stat name. Increment instead (matches what real
				// gameplay actually calls), and read back immediately after
				// to separate "the stat write itself didn't land" from "it
				// landed but the challenge system didn't react to it."
				float amount = (mode == WriteMode::Complete || write.kind == WriteKind::StatAtOnce) ? write.value : 1.0f;
				if (write.kind == WriteKind::StatDistinct && mode == WriteMode::Step)
				{
					// One click = one new distinct item. Which row is next is
					// tracked per goal by our own counter, NOT by reading the
					// stat: live-tested that the goal only counts picks made
					// after it became active, so an herb the player already
					// had (e.g. yarrow, from rank 1) still counts once
					// incremented here, and skipping already-nonzero stats
					// left the goal one short (14 of 15).
					sawDistinctStep = true;
					if (distinctRowLabel != write.label)
					{
						distinctRowLabel = write.label;
						distinctRowIndex = 0;
					}
					const int rowIndex = distinctRowIndex++;
					if (distinctStepDone || rowIndex != g_distinctStepsCredited[rage::Joaat(write.label)])
						continue;
					distinctStepDone = true;
					++g_distinctStepsCredited[rage::Joaat(write.label)];
				}
				if (write.kind == WriteKind::StatSum && mode == WriteMode::Step)
				{
					// The goal adds these stats together, so +1 on each row would
					// be +N total. Credit one per goal per click.
					if (!steppedSumGoals.insert(write.label).second)
						continue;
				}
				IncrementStatAndLog(write, id, Info(category), targetRank, verb, amount);
			}
			else if (write.kind == WriteKind::ScriptGoal)
			{
				Hash goalHash = static_cast<Hash>(rage::Joaat(write.label));
				int value = (mode == WriteMode::Complete) ? static_cast<int>(write.value + 0.5f) : 1;
				// CHAL_SET_GOAL_PROGRESS_INT live-tested and failed here
				// (Gambler rank 6, real ACW_GAMB_Rank_06_Blackjack_RHO/VAN
				// goal names) even though these ARE genuinely script-
				// sourced -- same SET-vs-ADD/INCREMENT split already found
				// for STAT_ID_SET_INT vs _STAT_ID_INCREMENT_INT. Using ADD
				// instead on the same theory.
				STATS::CHAL_ADD_GOAL_PROGRESS_INT(chalHash, goalHash, value);
				Log::Write("{}({}): added {} progress to script goal '{}' (rank {})",
					verb, Info(category).displayName, value, write.label, targetRank);
			}
			else if (write.kind == WriteKind::PointToPointHook)
			{
				// No sub-unit to step through -- a timed-ride goal is a
				// single native completion check with no persisted partial
				// state, so Step and Complete both just fire the same
				// one-shot unlock.
				std::uint64_t timedRideGoalIndex = static_cast<std::uint64_t>(write.value + 0.5f);
				// Stays armed AFTER this call returns -- the engine's own
				// periodic check is what fires it; TimedRideHook::Update()
				// (called from ScriptMain's loop) tears it down afterwards.
				if (!TimedRideHook::Arm(timedRideGoalIndex))
				{
					Log::Write("{}({}): FAILED to install native timed-ride completion hook for "
						"goal '{}' (rank {}) -- signature not found or MinHook error (see log above). "
						"Not counted as an applied write.",
						verb, Info(category).displayName, write.label, targetRank);
					continue;
				}

				Log::Write("{}({}): enabled timed-ride unlock hook for goal '{}' (rank {}, "
					"timed-ride goal index/RDX={:#x}) -- hook stays armed until the engine's next check "
					"unlocks it (or it times out).",
					verb, Info(category).displayName, write.label, targetRank, timedRideGoalIndex);
			}
			else if (write.kind == WriteKind::HorseCompendium)
			{
				// Each row is one breed's compendium entry (an atomic
				// spawn-and-break call). Complete applies every row (all 9
				// breeds for Horseman rank 10); Step credits ONE breed per
				// click, tracked by our own per-rank counter like
				// StatDistinct (no native reads a breed's broken state, so an
				// already-broken breed just costs a harmless redundant click).
				if (mode == WriteMode::Step)
				{
					sawDistinctStep = true;
					const int rowIndex = compendiumRowIndex++;
					if (distinctStepDone)
						continue;

					if (compendiumGoalStateUsable)
					{
						// The game tracks each breed as its own goal; skip the
						// ones it already considers complete.
						if (!STATS::CHAL_IS_GOAL_ACTIVE(chalHash, static_cast<Hash>(rage::Joaat(write.label))))
							continue;
					}
					else
					{
						const std::uint32_t counterKey = rage::Joaat(
							std::string("compendium:").append(Info(category).displayName).append(":").append(std::to_string(targetRank)));
						if (rowIndex != g_distinctStepsCredited[counterKey])
							continue;
						++g_distinctStepsCredited[counterKey];
					}
					distinctStepDone = true;
				}
				if (!SpawnAndBreakCompendiumHorse(write.modelHash, write.label))
				{
					Log::Write("{}({}): FAILED to spawn/break compendium horse for goal '{}' "
						"(rank {}, model {:#x}) -- model never loaded or CREATE_PED failed (see log "
						"above). Not counted as an applied write.",
						verb, Info(category).displayName, write.label, targetRank, write.modelHash);
					continue;
				}
			}
			else // WriteKind::Collectable
			{
				Hash itemHash = static_cast<Hash>(rage::Joaat(write.baseId));
				int amount = (mode == WriteMode::Complete) ? static_cast<int>(write.value + 0.5f) : 1;
				// Same native the real pickup state machine uses
				// (treasure_hunter.ysc.c's COLLECTABLE::_COLLECTABLE_INCREMENT_NUM_FOUND
				// call), just invoked directly instead of through a real pickup.
				COLLECTABLE::_COLLECTABLE_INCREMENT_NUM_FOUND(itemHash, amount);
				Log::Write("{}({}): marked collectable '{}' found x{} for goal '{}' (rank {})",
					verb, Info(category).displayName, write.baseId, amount, write.label, targetRank);
			}
			appliedCount++;
		}

		if (appliedCount == 0 && sawDistinctStep)
		{
			// Nothing left for Advance to credit. Say so on screen rather than
			// silently doing nothing.
			g_lastFailureReason = Localization::Text(Localization::Msg::AllItemsCredited);
			Log::Write("{}({}): every item for rank {} is already credited -- nothing to add.",
				verb, Info(category).displayName, targetRank);
			return false;
		}

		if (appliedCount == 0)
		{
			g_lastFailureReason = Localization::Text(Localization::Msg::NoKnownWrite);
			Log::Write("{}({}): no known write for rank {} yet -- unsupported goal type "
				"(group-stat, see CLAUDE.md). No change made.",
				verb, Info(category).displayName, targetRank);
			return false;
		}

		Log::Write("{}({}): applied {} write(s) for rank {} (mode={}) -- fire-and-forget, "
			"not polling for the rank counter to move. Check the menu's live Rank X/Y readout "
			"or the log for the real outcome.",
			verb, Info(category).displayName, appliedCount, targetRank, mode == WriteMode::Step ? "step" : "complete");
		return true;
	}

	bool AdvanceRank(Category category)
	{
		return ApplyRankProgress(category, WriteMode::Step);
	}

	int CompleteChallenge(Category category)
	{
		return ApplyRankProgress(category, WriteMode::Complete) ? 1 : 0;
	}
}
